package com.example.opusreader

class IdConverter {
    companion object {
        @JvmStatic
        fun getOperatorById(id: UInt): String {
            return when (id) {
                4u -> "ARTM"
                8u -> "STM"
                12u -> "RTL"
                16u -> "RTM"
                20u -> "RTC"
                24u -> "STL"
                64u -> "STLévis"
                else -> "Unknown (id: $id)"
            }
        }

        fun getLineById(operatorId: UInt, lineId: UInt): String {
            return when (operatorId) {
                8u -> this.getSTMLineById(lineId)
                12u -> this.getRTLLineById(lineId)
                16u -> this.getRTMLineById(lineId)
                20u -> this.getRTCLineById(lineId)
                24u -> this.getSTLLineById(lineId)
                64u -> this.getSTLevisLineById(lineId)
                else -> "Unknown (operatorId: $operatorId)"
            }
        }

        private fun getSTMLineById(id: UInt): String {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                1u -> "1 - Ligne Verte"
                2u -> "2 - Ligne Orange"
                224u -> "2 - Ligne Orange (zone B)"
                3u -> "4 - Ligne Jaune"
                4u -> "5 - Ligne Bleue"
                517u -> "10 De Lorimier"
                518u -> "11 Parc-du-Mont-Royal / Ridgewood"
                519u -> "12 Île-des-Soeurs"
                520u -> "13 Christophe-Colomb"
                521u -> "14 Atateken"
                522u -> "15 Sainte-Catherine"
                523u -> "16 Graham"
                524u -> "17 Décarie"
                525u -> "18 Beaubien"
                526u -> "19 Chabanel / Marché Central"
                527u -> "21 Place du Commerce"
                528u -> "22 Notre-Dame"
                529u -> "24 Sherbrooke"
                530u -> "25 Angus"
                531u -> "26 Mercier-Est"
                532u -> "27 Boulevard Saint-Joseph"
                533u -> "28 Honoré-Beaugrand"
                534u -> "29 Rachel"
                535u -> "30 Saint-Denis / Saint-Hubert"
                536u -> "31 Saint-Denis"
                537u -> "32 Lacordaire"
                538u -> "33 Langelier"
                539u -> "34 Sainte-Catherine"
                540u -> "35 Griffintown"
                541u -> "36 Monk"
                542u -> "37 Jolicoeur"
                543u -> "39 Des Grandes-Prairies"
                544u -> "40 Henri-Bourassa-Est"
                545u -> "41 Quartier Saint-Michel / Ahuntsic"
                546u -> "43 Monselet"
                547u -> "44 Armand-Bombardier"
                548u -> "45 Papineau"
                549u -> "46 Casgrain"
                550u -> "47 Masson"
                551u -> "48 Perras"
                552u -> "49 Maurice-Duplessis"
                553u -> "51 Édouard-Montpetit"
                554u -> "52 de Liège"
                555u -> "54 Charland / Chabanel"
                556u -> "55 Boulevard Saint-Laurent"
                557u -> "56 Saint-Hubert"
                558u -> "57 Pointe-Saint-Charles"
                559u -> "58 Wellington"
                560u -> "61 Wellington"
                561u -> "63 Girouard"
                562u -> "64 Grenet"
                563u -> "66 The Boulevard"
                564u -> "67 Saint-Michel"
                565u -> "68 Pierrefonds"
                566u -> "69 Gouin"
                567u -> "70 Bois-Franc"
                568u -> "71 Du Centre"
                569u -> "72 Alfred-Nobel"
                570u -> "73 Dalton"
                571u -> "74 Bridge"
                572u -> "75 De la Commune"
                573u -> "78 Laurendeau"
                574u -> "80 Avenue du Parc"
                575u -> "81 Saint-Jean-Baptiste"
                576u -> "85 Hochelaga"
                577u -> "86 Pointe-aux-Trembles"
                578u -> "90 Saint-Jacques"
                579u -> "92 Jean-Talon Ouest"
                580u -> "93 Jean-Talon"
                581u -> "94 D'Iberville"
                582u -> "95 Bélanger"
                583u -> "97 Avenue-du-Mont-Royal"
                584u -> "99 Villeray"
                585u -> "100 Crémazie"
                586u -> "101 Saint-Patrick"
                587u -> "102 Somerled"
                588u -> "103 Monkland"
                589u -> "104 Cavendish"
                590u -> "105 Sherbrooke"
                591u -> "106 Newman"
                592u -> "107 Verdun"
                593u -> "108 Bannantyne"
                594u -> "109 Boulevard Shevchenko"
                595u -> "110 Centrale"
                596u -> "112 Airlie"
                597u -> "113 Lapierre"
                598u -> "115 Paré"
                599u -> "116 Lafleur / Norman"
                600u -> "117 O'Brien"
                601u -> "119 Rockland"
                602u -> "121 Sauvé / Côte-Vertu"
                603u -> "123 Dollard"
                604u -> "124 Victoria"
                605u -> "125 Ontario"
                606u -> "126 Thimens / Grenet"
                607u -> "128 Saint-Laurent"
                608u -> "129 Côte-Sainte-Catherine"
                609u -> "131 De l'Assomption"
                610u -> "135 De l'Esplanade"
                611u -> "136 Viau"
                612u -> "138 Notre-Dame-de-Grâce"
                613u -> "139 Pie-IX"
                614u -> "140 Fleury"
                615u -> "141 Jean-Talon Est"
                616u -> "144 Avenue des Pins"
                617u -> "146 Christophe-Colomb / Meilleur"
                618u -> "150 René-Lévesque"
                619u -> "160 Barclay"
                620u -> "161 Van Horne"
                621u -> "162 Westminster"
                622u -> "164 Dudemaine"
                623u -> "165 Côte-des-Neiges"
                624u -> "166 Queen-Mary"
                625u -> "168 Cité-du-Havre"
                626u -> "170 Keller"
                627u -> "171 Henri-Bourassa"
                628u -> "172 Du Golf"
                629u -> "174 Côte-Vertu-Ouest"
                630u -> "175 Griffith / Saint-François"
                631u -> "176 Berlioz"
                632u -> "177 Thimens"
                633u -> "178 Pointe-Nord / Île-des-Soeurs"
                634u -> "179 De l'Acadie"
                635u -> "180 De Salaberry"
                636u -> "183 Gouin Est"
                637u -> "185 Sherbrooke"
                638u -> "186 Sherbrooke-Est"
                639u -> "187 René-Lévesque"
                640u -> "188 Couture"
                641u -> "189 Notre-Dame"
                642u -> "191 Broadway / Provost"
                643u -> "192 Robert"
                644u -> "193 Jarry"
                645u -> "195 Sherbrooke / Notre-Dame"
                646u -> "196 Parc-Industriel-Lachine"
                647u -> "197 Rosemont"
                648u -> "200 Sainte-Anne-de-Bellevue"
                649u -> "201 Saint-Charles / Saint-Jean"
                650u -> "202 Dawson"
                651u -> "203 Carson"
                652u -> "204 Cardinal"
                653u -> "205 Gouin"
                654u -> "206 Roger-Pilon"
                655u -> "207 Jacques-Bizard"
                656u -> "208 Brunswick"
                657u -> "209 Des Sources"
                658u -> "211 Bord-du-Lac"
                659u -> "212 Sainte-Anne"
                660u -> "213 Parc-Industriel-Saint-Laurent"
                661u -> "215 Henri-Bourassa"
                662u -> "216 Transcanadienne"
                663u -> "217 Anse-à-l'Orme"
                664u -> "218 Antoine-Faucon"
                665u -> "219 Chemin Sainte-Marie"
                666u -> "220 Kieran"
                667u -> "225 Hymus"
                668u -> "350 Verdun / LaSalle"
                669u -> "353 Lacordaire / Maurice-Duplessis"
                670u -> "354 Sainte-Anne-de-Bellevue / Centre-ville"
                671u -> "355 Pie-IX"
                672u -> "356 Lachine / YUL Aéroport / Des Sources"
                673u -> "357 Saint-Michel"
                674u -> "358 Sainte-Catherine"
                675u -> "359 Papineau"
                676u -> "360 Avenue des Pins"
                677u -> "361 Saint-Denis"
                678u -> "362 Hochelaga / Notre-Dame"
                679u -> "363 Boulevard Saint-Laurent"
                680u -> "364 Sherbrooke / Joseph-Renaud"
                681u -> "365 Avenue du Parc"
                682u -> "368 Avenue-du-Mont-Royal"
                683u -> "369 Côte-des-Neiges"
                684u -> "370 Rosemont"
                685u -> "371 Décarie"
                686u -> "372 Jean-Talon"
                687u -> "376 Pierrefonds / Centre-ville"
                688u -> "378 Sauvé / YUL Aéroport"
                689u -> "380 Henri-Bourassa"
                690u -> "382 Pierrefonds / Saint-Charles"
                691u -> "401 Express Saint-Charles"
                692u -> "405 Express Bord-du-Lac"
                693u -> "406 Express Newman"
                694u -> "407 Express Île-Bizard"
                695u -> "409 Express Des Sources"
                696u -> "410 Express Notre-Dame"
                697u -> "411 Express Lionel-Groulx"
                698u -> "419 Express John Abbott"
                699u -> "420 Express Notre-Dame-de-Grâce"
                700u -> "425 Express Anse-à-l'Orme"
                701u -> "427 Express Saint-Joseph"
                702u -> "428 Express Parcs industriels de l'Est"
                703u -> "430 Express Pointe-aux-Trembles"
                704u -> "432 Express Lacordaire"
                705u -> "439 Express Pie-IX"
                706u -> "440 Express Charleroi"
                707u -> "444 Express Cégep Marie-Victorin"
                708u -> "445 Express Papineau"
                709u -> "448 Express Maurice-Duplessis"
                710u -> "449 Express Rivière-des-Prairies"
                711u -> "460 Express Métropolitaine"
                712u -> "465 Express Côte-des-Neiges"
                713u -> "467 Express Saint-Michel"
                714u -> "468 Express Pierrefonds / Gouin"
                715u -> "469 Express Henri-Bourassa"
                716u -> "470 Express Pierrefonds"
                717u -> "475 Express Dollard-des-Ormeaux"
                718u -> "480 Express du Parc"
                719u -> "485 Express Antoine-Faucon"
                720u -> "486 Express Sherbrooke"
                721u -> "487 Express Bout-de-l'Île"
                722u -> "491 Express Lachine"
                723u -> "495 Express Lachine / LaSalle"
                724u -> "496 Express Victoria"
                725u -> "711 Parc-du-Mont-Royal / Oratoire"
                726u -> "715 Vieux-Montréal / Vieux-Port"
                727u -> "747 YUL Aéroport  / Centre-Ville"
                728u -> "767 La Ronde / Station Jean-Drapeau"
                729u -> "768 Plage Jean-Doré / Station Jean-Drapeau"
                730u -> "769 La Ronde / Station Papineau"
                731u -> "777 Jean-Drapeau / Casino / Bonaventure"
                732u -> "811 Navette Services santé"
                733u -> "822 Navette Longue-Pointe"
                734u -> "968 Trainbus Roxboro / Côte-Vertu"
                else -> "Unknown (lineId: $id)"
            }
        }

        private fun getRTLLineById(id: UInt): String {
            return when (id) {
                // TODO Find ids of all lines
                //   (Id of the line is on 9bits so higher
                //   than 512u means it's not known yet)
                513u -> "1 Desaulniers / Victoria / Windsor"
                514u -> "3 Secteur Laflèche"
                515u -> "4 Taschereau / Payer / DIX30"
                516u -> "5 Auteuil / Mtée St-Hubert / Maisonneuve"
                517u -> "6 Victoria"
                518u -> "8 Ch. Chambly / Cousineau / Promenades St-Bruno"
                519u -> "9 Secteurs L-M St-Hubert"
                520u -> "10 Roland-Therrien / Belcourt"
                521u -> "13 Riverside / Secteurs P-V Brossard"
                522u -> "14 Rome / DIX30"
                523u -> "15 Riverside / Alexandra / Churchill"
                524u -> "16 Nobert / King-George / Adoncour"
                525u -> "17 Roland-Therrien / Roberval"
                526u -> "19 Davis"
                527u -> "20 Jean-Paul-Vincent / Beauharnois"
                528u -> "21 Grande-Allée / du Quartier"
                529u -> "22 Gare Longueuil - St-Hubert / Sect. B Vieux-Longueuil"
                530u -> "23 Ste-Hélène / Jacques-Cartier"
                531u -> "25 Parcs industriels Vieux-Longueuil / Boucherville"
                532u -> "28 Ch. Chambly / Savane / ENA"
                533u -> "29 Collectivité Nouvelle"
                534u -> "30 Secteurs P-V Brossard"
                535u -> "31 Secteurs R-S-T Brossard / St-Laurent"
                536u -> "32 Secteur B Brossard / Mountainview"
                537u -> "33 Secteurs M-N-O Brossard"
                538u -> "34 Secteur A Brossard / Bellevue"
                539u -> "37 Simard / du Béarn"
                540u -> "38 Chevrier / Secteur B Brossard"
                541u -> "41 Rome / Milan"
                542u -> "42 Gaétan-Boucher / Parc de la Cité"
                543u -> "43 Milan / Rome"
                544u -> "44 Secteurs M-N-O Brossard"
                545u -> "46 Secteurs R-S-T Brossard"
                546u -> "47 Secteurs R-S-T Brossard"
                547u -> "49 Secteurs R-S Brossard"
                548u -> "50 Bienville / Orchard / Prince-Charles"
                549u -> "54 Tiffin / St-Georges / Taschereau"
                550u -> "55 Victoria / Wellington"
                551u -> "59 Montgomery / Gareau"
                552u -> "60 Milan / Gaétan-Boucher / Promenades St-Bruno"
                553u -> "61 Boucherville / Station Radisson"
                554u -> "71 Curé-Poirier"
                555u -> "73 Joliette / de Lyon"
                556u -> "74 St-Laurent / Secteur Bellerive"
                557u -> "75 Quinn / Brébeuf"
                558u -> "76 Roland-Therrien / Roberval"
                559u -> "77 Taschereau / Coteau-Rouge / Cégep É.-Montpetit"
                560u -> "78 Adoncour / du Colisée"
                561u -> "80 De Montarville / Carrefour de la Rive-Sud"
                562u -> "81 du Fort-St-Louis / Marie-Victorin"
                563u -> "82 Marie-Victorin / du Fort-St-Louis"
                564u -> "83 De Montarville / Samuel-De Champlain"
                565u -> "84 Samuel-De Champlain / De Montarville"
                566u -> "85 Îles-Percées / de Mortagne / de Gascogne"
                567u -> "86 Samuel-De Champlain / De Montarville / TCV"
                568u -> "87 Marie-Victorin / du Fort St-Louis / TCV"
                569u -> "88 Ch. Chambly / Mountainview"
                570u -> "93 Gare St-Bruno / Montarville / Y.-Duckett"
                571u -> "98 Parc industriel St-Bruno / Parent"
                572u -> "99 Promenades St-Bruno / Saint-Bruno-de-Montarville"
                573u -> "120 Fernand-Lafontaine / Stationnement de Mortagne"
                574u -> "123 Jacques-Cartier / Parcs industriels"
                575u -> "125 Pratt & Whitney / Lumenpulse"
                576u -> "128 Zone aéroportuaire / Parc industriel St-Bruno"
                577u -> "132 DIX30 / Parc de la Cité / Mountainview"
                578u -> "160 Milan / Gaétan-Boucher / Centre-ville St-Bruno"
                579u -> "161 R.-Therrien / J.-Cartier / De Montarville"
                580u -> "170 Station Papineau / Ste-Hélène / J.-Cartier"
                581u -> "180 De Montarville / des Sureaux"
                582u -> "185 Ampère / Gay-Lussac"
                583u -> "192 Station Brossard / Montarville / Y.-Duckett"
                584u -> "199 Seigneurial / Grand Boulevard"
                585u -> "214 Station Brossard / de Rome / St-Laurent"
                586u -> "284 Navette Boucherville"
                587u -> "410 Express Roland-Therrien / Belcourt"
                588u -> "417 Express Roland-Therrien / Roberval"
                589u -> "421 Grande-Allée / A.-Frappier"
                590u -> "428 Zone aéroportuaire / Agence Spatiale canadienne"
                591u -> "442 Cousineau / Pacific"
                592u -> "461 Express de Touraine / de Montarville / Radisson"
                593u -> "462 Touraine-Mortagne-Radisson-HMR-Inst.cardio"
                594u -> "500 École Saint-Lambert International High School"
                595u -> "503 École Centennial Regional High School"
                596u -> "505 École Centennial Regional High School"
                597u -> "521 École Centennial Regional High School"
                598u -> "524 École Centennial Regional High School"
                599u -> "525 École Centennial Regional High School"
                600u -> "526 École Centennial Regional High School"
                601u -> "530 École Centennial Regional High School"
                602u -> "532 École Centennial Regional High School"
                603u -> "533 École Centennial Regional High School"
                604u -> "534 École Centennial Regional High School"
                605u -> "535 École Centennial Regional High School"
                606u -> "536 École Centennial Regional High School"
                607u -> "538 École Heritage Regional High School"
                608u -> "539 École Heritage Regional High School"
                609u -> "540 École Heritage Regional High School"
                610u -> "542 École Heritage Regional High School"
                611u -> "544 École Centennial Regional High School"
                612u -> "546 École Centennial Regional High School"
                613u -> "547 École Centennial Regional High School"
                614u -> "549 École Centennial Regional High School"
                615u -> "550 École Centennial Regional High School"
                616u -> "551 École Centennial Regional High School"
                617u -> "565 École Saint-Lambert International High School"
                618u -> "570 École Saint-Lambert International High School"
                619u -> "572 École Saint-Lambert International High School"
                620u -> "575 École Saint-Lambert International High School"
                621u -> "580 École Saint-Lambert International High School"
                622u -> "600 Écoles privées"
                623u -> "601 École de l'Agora"
                624u -> "602 École de l'Agora"
                625u -> "604 École de l'Agora"
                626u -> "605 École de l'Agora"
                627u -> "606 Écoles privées"
                628u -> "607 École de l'Agora"
                629u -> "608 École André-Laurendeau et Cégep Édouard-Montpetit"
                630u -> "609 École de l'Agora"
                631u -> "613 Écoles privées"
                632u -> "614 Écoles privées"
                633u -> "616 École Gérard-Filion"
                634u -> "618 Écoles privées"
                635u -> "620 Collège Français"
                636u -> "624 École St-Jean-Baptiste"
                637u -> "640 École Antoine-Brossard"
                638u -> "644 École Antoine-Brossard"
                639u -> "650 École Antoine-Brossard"
                640u -> "653 École Antoine-Brossard"
                641u -> "656 École Antoine-Brossard"
                642u -> "660 École Antoine-Brossard"
                643u -> "664 École Antoine-Brossard"
                644u -> "665 École Antoine-Brossard"
                645u -> "670 École Antoine-Brossard"
                646u -> "671 École Jacques-Rousseau"
                647u -> "672 École Jacques-Rousseau"
                648u -> "673 École Jacques-Rousseau"
                649u -> "674 École Antoine-Brossard"
                650u -> "675 École Jacques-Rousseau"
                651u -> "676 École Jacques-Rousseau"
                652u -> "678 École Jacques-Rousseau"
                653u -> "683 Cégep Édouard-Montpetit"
                654u -> "684 École Antoine-Brossard"
                655u -> "689 École Antoine-Brossard"
                656u -> "690 École Antoine-Brossard"
                657u -> "691 École Lucille-Teasdale"
                658u -> "692 École Lucille-Teasdale"
                659u -> "693 École Lucille-Teasdale"
                660u -> "694 École Lucille-Teasdale"
                661u -> "695 École Lucille-Teasdale"
                662u -> "696 École Lucille-Teasdale"
                663u -> "697 École Lucille-Teasdale - Secteur Chevrier"
                else -> "Unknown (lineId: $id)"
            }
        }

        private fun getRTMLineById(id: UInt): String {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> "11 Vaudreuil-Hudson"
                514u -> "12 Saint-Jérôme"
                515u -> "13 Mont-Saint-Hilaire"
                516u -> "14 Candiac"
                517u -> "15 Mascouche"
                518u -> "12 Saint-Jérôme (zone B)"
                519u -> "13 Mont-Saint-Hilaire (zone B)"
                520u -> "11 Vaudreuil-Hudson (zone C)"
                521u -> "12 Saint-Jérôme (zone C)"
                522u -> "13 Mont-Saint-Hilaire (zone C)"
                523u -> "14 Candiac (zone C)"
                524u -> "15 Mascouche (zone C)"
                else -> "Unknown (lineId: $id)"
            }
        }

        private fun getRTCLineById(id: UInt): String {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> "1 Station Belvédère - Gare fluviale / Cap-Blanc"
                514u -> "107 Gare du Palais - Pointe-de-Sainte-Foy"
                515u -> "11 Gare fluviale - Pointe-de-Sainte-Foy"
                516u -> "11G C.-Laforte / McCartney"
                517u -> "13 Saint-Louis/Sainte-Foy Centre/du Versant-Nord - Du Versant-Nord/Sainte-Foy Centre/Saint-Louis"
                518u -> "133 Vieux-Québec - Terminus de la Faune"
                519u -> "136 Colline Parlementaire - Montagne-des-Roches"
                520u -> "13A École secondaire De Rochebelle - De Terrebonne / de La Suète"
                521u -> "13B École secondaire De Rochebelle - Des Sapins / du Versant-Nord"
                522u -> "14 Pointe-de-Sainte-Foy - Cap-Rouge"
                523u -> "14A Collège des Compagnons - De la Rivière / du Domaine"
                524u -> "14G Collège Jésus-Marie de Sillery - Des Carougeois / J.-C.-Cantin"
                525u -> "15 Pointe-de-Sainte-Foy - Cap-Rouge"
                526u -> "15A Collège des Compagnons - de la Prom.-des-Soeurs / J.-C.-Cantin"
                527u -> "15B Collège des Compagnons - de la Prom-des-Soeurs / Escoffier"
                528u -> "16 Sillery / U. Laval / Sainte-Foy Centre - U. Laval / Sillery / Sainte-Foy Centre"
                529u -> "18 Gare du Palais - Université Laval"
                530u -> "185 Station Belvédère / Sainte-Foy Centre - Neufchâtel"
                531u -> "19 Grand Théâtre - Limoilou"
                532u -> "214 Gare du Palais - Cap-Rouge"
                533u -> "215 Gare du Palais - Cap-Rouge"
                534u -> "22 Sainte-Foy Centre - Terminus Les Saules"
                535u -> "230 Colline Parlementaire - Terminus de la Faune"
                536u -> "236 Colline Parlementaire - Station des Roses"
                537u -> "238 Colline Parlementaire - Guillaume-Mathieu"
                538u -> "239 Colline Parlementaire - Terminus de la Faune"
                539u -> "25 Place D'Youville / Gare du Palais - Pointe-de-Sainte-Foy"
                540u -> "250 Colline Parlementaire - Terminus Chute-Montmorency"
                541u -> "251 Colline Parlementaire - Parc-O-Bus Sainte-Anne"
                542u -> "253 Colline Parlementaire - Courville"
                543u -> "254 Colline Parlementaire - Sainte-Thérèse-de-Lisieux"
                544u -> "255 Colline Parlementaire - Sainte-Thérèse-de-Lisieux"
                545u -> "257 Colline Parlementaire - Sainte-Thérèse-de-Lisieux"
                546u -> "258 Colline Parlementaire - Sainte-Thérèse-de-Lisieux"
                547u -> "25G Pointe-de-Sainte-Foy"
                548u -> "272 Colline Parlementaire - Loretteville"
                549u -> "273 Colline Parlementaire - Loretteville Sud"
                550u -> "274 Colline Parlementaire - Neufchâtel"
                551u -> "277 Colline Parlementaire - Val-Bélair"
                552u -> "279 Colline Parlementaire - L'Ancienne-Lorette"
                553u -> "28 Colline Parlementaire - 51e Rue Est"
                554u -> "280 Place Jacques-Cartier / colline Parlementaire - L'Ancienne-Lorette"
                555u -> "281 Colline Parlementaire - Neufchâtel"
                556u -> "282 Colline Parlementaire - Lac-Saint-Charles"
                557u -> "283 Gare du Palais - Champigny"
                558u -> "284 Colline Parlementaire - Loretteville"
                559u -> "289 Colline Parlementaire - Saint-Émile"
                560u -> "29 Parc Colbert Ouest - Place Jacques-Cartier"
                561u -> "290 Vieux-Québec - Loretteville"
                562u -> "292 Place Jacques-Cartier - Saint-Augustin"
                else -> "Unknown (lineId: $id)"
            }
        }

        private fun getSTLLineById(id: UInt): String {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> "12 Pont-Viau / Métro Cartier"
                514u -> "144 Métro Côte-Vertu / Sainte-Dorothée"
                515u -> "151 Sainte-Rose / Métro Côte-Vertu"
                516u -> "16 Métro Montmorency / Laval-des-Rapides / Armand-Frappier"
                517u -> "17 Auteuil / Métro Cartier"
                518u -> "2 Métro Henri-Bourassa / Métro Montmorency"
                519u -> "20 Métro Cartier / Chomedey"
                520u -> "22 Saint-François / Métro Cartier"
                521u -> "222 Saint-Vincent-De-Paul / Métro Cartier"
                522u -> "24 Métro Cartier / Sainte-Dorothée"
                523u -> "252 Saint-François / Métro Henri-Bourassa"
                524u -> "26 Métro Montmorency / Gare Sainte-Dorothée"
                525u -> "27 Gare Vimont / Métro Cartier"
                526u -> "31 Auteuil / Métro Henri-Bourassa"
                527u -> "313 Chomedey / Métro Côte-Vertu"
                528u -> "33 Métro Montmorency / Métro Cartier"
                529u -> "345 Gare Vimont / Métro Henri-Bourassa"
                530u -> "36 Métro Montmorency / Chomedey"
                531u -> "360 Navette Centre-Ville (Gratuit)"
                532u -> "37 Sainte-Rose / Métro Cartier"
                533u -> "39 Auteuil / Terminus Le Carrefour"
                534u -> "40 Métro Montmorency / Chomedey"
                535u -> "41 Auteuil / Métro Cartier"
                536u -> "42 Saint-François / Terminus Le Carrefour"
                537u -> "43 Auteuil / Métro Cartier"
                538u -> "45 Auteuil / Métro Montmorency"
                539u -> "46 Laval-Ouest / Métro Montmorency"
                540u -> "48 Gare Vimont / Métro Cartier"
                541u -> "50 Saint-Vincent-De-Paul / Terminus Le Carrefour"
                542u -> "52 Saint-François / Métro Henri-Bourassa"
                543u -> "55 Laval-Ouest / Métro Henri-Bourassa"
                544u -> "56 Métro Montmorency / Sainte-Dorothée"
                545u -> "58 Saint-Vincent-De-Paul / Métro Cartier"
                546u -> "60 Métro Cartier / Chomedey"
                547u -> "61 Fabreville / Métro Montmorency"
                548u -> "63 Gare Sainte-Rose / Métro Cartier"
                549u -> "65 Gare Sainte-Rose / Métro Montmorency"
                550u -> "66 Terminus Le Carrefour / Sainte-Dorothée"
                551u -> "70 Métro Cartier / Métro Montmorency"
                552u -> "713 Sainte-Dorothée / Métro Côte-Vertu"
                553u -> "73 Fabreville / Métro Cartier"
                554u -> "730 Gare Sainte-Dorothée / Montréal"
                555u -> "74 Saint-François / Métro Cartier"
                556u -> "744 Métro Côte-Vertu / Gare Sainte-Dorothée"
                557u -> "76 Métro Montmorency / Gare Sainte-Dorothée"
                558u -> "901 Saint-François / Métro Cartier"
                559u -> "902 Terminus Le Carrefour / Métro Côte-Vertu"
                560u -> "903 Gare Sainte-Dorothée / Métro Montmorency"
                561u -> "925 Saint-François / Métro Radisson"
                562u -> "942 Saint-François / Métro Montmorency"
                else -> "Unknown (lineId: $id)"
            }
        }

        private fun getSTLevisLineById(id: UInt): String {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> "11"
                514u -> "111"
                515u -> "115"
                516u -> "119"
                517u -> "11A"
                518u -> "125"
                519u -> "126"
                520u -> "127"
                521u -> "129"
                522u -> "13"
                523u -> "131"
                524u -> "135"
                525u -> "136"
                526u -> "137"
                527u -> "139"
                528u -> "15"
                529u -> "155"
                530u -> "156"
                531u -> "158"
                532u -> "22"
                533u -> "221"
                534u -> "222"
                535u -> "225"
                536u -> "23"
                537u -> "231"
                538u -> "232"
                539u -> "235"
                540u -> "24"
                541u -> "241"
                542u -> "242"
                543u -> "245"
                544u -> "246"
                545u -> "31"
                546u -> "311"
                547u -> "325"
                548u -> "34"
                549u -> "345"
                550u -> "34E"
                551u -> "35"
                552u -> "351"
                553u -> "355"
                554u -> "36"
                555u -> "36E"
                556u -> "37"
                557u -> "375"
                558u -> "37E"
                559u -> "38"
                560u -> "381"
                561u -> "385"
                562u -> "38E"
                563u -> "39"
                564u -> "42E"
                565u -> "43E"
                566u -> "65"
                567u -> "ECQ"
                568u -> "ELQ"
                569u -> "EOQ"
                570u -> "ESQ"
                571u -> "L1 Lévisien 1"
                572u -> "L2 Lévisien 2"
                573u -> "L3 Lévisien 3"
                else -> "Unknown (lineId: $id)"
            }
        }
    }
}