package com.example.opusreader


data class FareProduct(val name: String)
data class Operator(val name: String, val color: String, val imageId: Int)
data class Line(val id: String, val name: String, val color: String, val textColor: String, val icon: Int)

class IdConverter {
    companion object {
        fun getFareProductById(id: UInt): FareProduct {
            return when (id) {
                3316801u -> FareProduct("2 passages, Bus")
                3316865u -> FareProduct("10 passages, Bus")
                3314625u -> FareProduct("2 passages, Tous modes A")
                3314689u -> FareProduct("1 passage, Tous modes AB")
                3314753u -> FareProduct("2 passages, Tous modes AB")
                3312577u -> FareProduct("10 passages, Tous modes AB")
                3322369u -> FareProduct("24hrs, Tous modes AB")
                3321601u -> FareProduct("3 jours, Tous modes AB")
                3310337u -> FareProduct("1 passage, Tous modes ABC")
                3305921u -> FareProduct("Soirée illimité")
                3305985u -> FareProduct("Week-end illimité")
                else -> FareProduct("Inconnu (${id})")
            }
        }

        fun getOperatorById(id: UInt): Operator {
            return when (id) {
                4u -> Operator("ARTM", "#007373", R.drawable.unknown)
                8u -> Operator("STM", "#00aeef", R.drawable.stm)
                12u -> Operator("RTL", "#9e2536", R.drawable.rtl)
                16u -> Operator("exo", "#000000", R.drawable.exo)
                20u -> Operator("RTC", "#003878", R.drawable.rtc)
                24u -> Operator("STL", "#151f6d", R.drawable.stl)
                64u -> Operator("STLévis", "#0091b3", R.drawable.stlevis)
                else -> Operator("Unknown (id: $id)", "#696969", R.drawable.unknown)
            }
        }

        fun getLineById(operatorId: UInt, lineId: UInt): Line {
            return when (operatorId) {
                8u -> this.getSTMLineById(lineId)
                12u -> this.getRTLLineById(lineId)
                16u -> this.getEXOLineById(lineId)
                20u -> this.getRTCLineById(lineId)
                24u -> this.getSTLLineById(lineId)
                64u -> this.getSTLevisLineById(lineId)
                else -> Line("", "Unknown (operatorId: $operatorId)", "#696969", "#ffffff", R.drawable.unknown)
            }
        }

        private fun getSTMLineById(id: UInt): Line {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                1u -> Line("1", "Ligne Verte", "#008e4f", "#ffffff", R.drawable.metro)
                2u -> Line("2", "Ligne Orange", "#ef8122", "#ffffff", R.drawable.metro)
                224u -> Line("2", "Ligne Orange (zone B)", "#ef8122", "#ffffff", R.drawable.metro)
                3u -> Line("4", "Ligne Jaune", "#ffe300", "#ffffff", R.drawable.metro)
                4u -> Line("5", "Ligne Bleue", "#0083c9", "#ffffff", R.drawable.metro)
                517u -> Line("10", "De Lorimier", "#009ee0", "#ffffff", R.drawable.bus)
                518u -> Line("11", "Parc-du-Mont-Royal / Ridgewood", "#009ee0", "#ffffff", R.drawable.bus)
                519u -> Line("12", "Île-des-Soeurs", "#009ee0", "#ffffff", R.drawable.bus)
                520u -> Line("13", "Christophe-Colomb", "#009ee0", "#ffffff", R.drawable.bus)
                521u -> Line("14", "Atateken", "#009ee0", "#ffffff", R.drawable.bus)
                522u -> Line("15", "Sainte-Catherine", "#009ee0", "#ffffff", R.drawable.bus)
                523u -> Line("16", "Graham", "#009ee0", "#ffffff", R.drawable.bus)
                524u -> Line("17", "Décarie", "#009ee0", "#ffffff", R.drawable.bus)
                525u -> Line("18", "Beaubien", "#781b7d", "#ffffff", R.drawable.bus)
                526u -> Line("19", "Chabanel / Marché Central", "#009ee0", "#ffffff", R.drawable.bus)
                527u -> Line("21", "Place du Commerce", "#009ee0", "#ffffff", R.drawable.bus)
                528u -> Line("22", "Notre-Dame", "#009ee0", "#ffffff", R.drawable.bus)
                529u -> Line("24", "Sherbrooke", "#781b7d", "#ffffff", R.drawable.bus)
                530u -> Line("25", "Angus", "#009ee0", "#ffffff", R.drawable.bus)
                531u -> Line("26", "Mercier-Est", "#009ee0", "#ffffff", R.drawable.bus)
                532u -> Line("27", "Boulevard Saint-Joseph", "#009ee0", "#ffffff", R.drawable.bus)
                533u -> Line("28", "Honoré-Beaugrand", "#009ee0", "#ffffff", R.drawable.bus)
                534u -> Line("29", "Rachel", "#009ee0", "#ffffff", R.drawable.bus)
                535u -> Line("30", "Saint-Denis / Saint-Hubert", "#009ee0", "#ffffff", R.drawable.bus)
                536u -> Line("31", "Saint-Denis", "#009ee0", "#ffffff", R.drawable.bus)
                537u -> Line("32", "Lacordaire", "#781b7d", "#ffffff", R.drawable.bus)
                538u -> Line("33", "Langelier", "#781b7d", "#ffffff", R.drawable.bus)
                539u -> Line("34", "Sainte-Catherine", "#009ee0", "#ffffff", R.drawable.bus)
                540u -> Line("35", "Griffintown", "#009ee0", "#ffffff", R.drawable.bus)
                541u -> Line("36", "Monk", "#009ee0", "#ffffff", R.drawable.bus)
                542u -> Line("37", "Jolicoeur", "#009ee0", "#ffffff", R.drawable.bus)
                543u -> Line("39", "Des Grandes-Prairies", "#009ee0", "#ffffff", R.drawable.bus)
                544u -> Line("40", "Henri-Bourassa-Est", "#009ee0", "#ffffff", R.drawable.bus)
                545u -> Line("41", "Quartier Saint-Michel / Ahuntsic", "#009ee0", "#ffffff", R.drawable.bus)
                546u -> Line("43", "Monselet", "#009ee0", "#ffffff", R.drawable.bus)
                547u -> Line("44", "Armand-Bombardier", "#781b7d", "#ffffff", R.drawable.bus)
                548u -> Line("45", "Papineau", "#781b7d", "#ffffff", R.drawable.bus)
                549u -> Line("46", "Casgrain", "#009ee0", "#ffffff", R.drawable.bus)
                550u -> Line("47", "Masson", "#009ee0", "#ffffff", R.drawable.bus)
                551u -> Line("48", "Perras", "#781b7d", "#ffffff", R.drawable.bus)
                552u -> Line("49", "Maurice-Duplessis", "#781b7d", "#ffffff", R.drawable.bus)
                553u -> Line("51", "Édouard-Montpetit", "#781b7d", "#ffffff", R.drawable.bus)
                554u -> Line("52", "de Liège", "#009ee0", "#ffffff", R.drawable.bus)
                555u -> Line("54", "Charland / Chabanel", "#009ee0", "#ffffff", R.drawable.bus)
                556u -> Line("55", "Boulevard Saint-Laurent", "#781b7d", "#ffffff", R.drawable.bus)
                557u -> Line("56", "Saint-Hubert", "#009ee0", "#ffffff", R.drawable.bus)
                558u -> Line("57", "Pointe-Saint-Charles", "#009ee0", "#ffffff", R.drawable.bus)
                559u -> Line("58", "Wellington", "#009ee0", "#ffffff", R.drawable.bus)
                560u -> Line("61", "Wellington", "#009ee0", "#ffffff", R.drawable.bus)
                561u -> Line("63", "Girouard", "#009ee0", "#ffffff", R.drawable.bus)
                562u -> Line("64", "Grenet", "#781b7d", "#ffffff", R.drawable.bus)
                563u -> Line("66", "The Boulevard", "#009ee0", "#ffffff", R.drawable.bus)
                564u -> Line("67", "Saint-Michel", "#781b7d", "#ffffff", R.drawable.bus)
                565u -> Line("68", "Pierrefonds", "#009ee0", "#ffffff", R.drawable.bus)
                566u -> Line("69", "Gouin", "#781b7d", "#ffffff", R.drawable.bus)
                567u -> Line("70", "Bois-Franc", "#009ee0", "#ffffff", R.drawable.bus)
                568u -> Line("71", "Du Centre", "#009ee0", "#ffffff", R.drawable.bus)
                569u -> Line("72", "Alfred-Nobel", "#009ee0", "#ffffff", R.drawable.bus)
                570u -> Line("73", "Dalton", "#009ee0", "#ffffff", R.drawable.bus)
                571u -> Line("74", "Bridge", "#009ee0", "#ffffff", R.drawable.bus)
                572u -> Line("75", "De la Commune", "#009ee0", "#ffffff", R.drawable.bus)
                573u -> Line("78", "Laurendeau", "#009ee0", "#ffffff", R.drawable.bus)
                574u -> Line("80", "Avenue du Parc", "#781b7d", "#ffffff", R.drawable.bus)
                575u -> Line("81", "Saint-Jean-Baptiste", "#009ee0", "#ffffff", R.drawable.bus)
                576u -> Line("85", "Hochelaga", "#009ee0", "#ffffff", R.drawable.bus)
                577u -> Line("86", "Pointe-aux-Trembles", "#009ee0", "#ffffff", R.drawable.bus)
                578u -> Line("90", "Saint-Jacques", "#781b7d", "#ffffff", R.drawable.bus)
                579u -> Line("92", "Jean-Talon Ouest", "#009ee0", "#ffffff", R.drawable.bus)
                580u -> Line("93", "Jean-Talon", "#009ee0", "#ffffff", R.drawable.bus)
                581u -> Line("94", "D'Iberville", "#009ee0", "#ffffff", R.drawable.bus)
                582u -> Line("95", "Bélanger", "#009ee0", "#ffffff", R.drawable.bus)
                583u -> Line("97", "Avenue-du-Mont-Royal", "#781b7d", "#ffffff", R.drawable.bus)
                584u -> Line("99", "Villeray", "#009ee0", "#ffffff", R.drawable.bus)
                585u -> Line("100", "Crémazie", "#009ee0", "#ffffff", R.drawable.bus)
                586u -> Line("101", "Saint-Patrick", "#009ee0", "#ffffff", R.drawable.bus)
                587u -> Line("102", "Somerled", "#009ee0", "#ffffff", R.drawable.bus)
                588u -> Line("103", "Monkland", "#781b7d", "#ffffff", R.drawable.bus)
                589u -> Line("104", "Cavendish", "#009ee0", "#ffffff", R.drawable.bus)
                590u -> Line("105", "Sherbrooke", "#781b7d", "#ffffff", R.drawable.bus)
                591u -> Line("106", "Newman", "#009ee0", "#ffffff", R.drawable.bus)
                592u -> Line("107", "Verdun", "#009ee0", "#ffffff", R.drawable.bus)
                593u -> Line("108", "Bannantyne", "#009ee0", "#ffffff", R.drawable.bus)
                594u -> Line("109", "Boulevard Shevchenko", "#009ee0", "#ffffff", R.drawable.bus)
                595u -> Line("110", "Centrale", "#009ee0", "#ffffff", R.drawable.bus)
                596u -> Line("112", "Airlie", "#009ee0", "#ffffff", R.drawable.bus)
                597u -> Line("113", "Lapierre", "#009ee0", "#ffffff", R.drawable.bus)
                598u -> Line("115", "Paré", "#009ee0", "#ffffff", R.drawable.bus)
                599u -> Line("116", "Lafleur / Norman", "#009ee0", "#ffffff", R.drawable.bus)
                600u -> Line("117", "O'Brien", "#009ee0", "#ffffff", R.drawable.bus)
                601u -> Line("119", "Rockland", "#009ee0", "#ffffff", R.drawable.bus)
                602u -> Line("121", "Sauvé / Côte-Vertu", "#781b7d", "#ffffff", R.drawable.bus)
                603u -> Line("123", "Dollard", "#009ee0", "#ffffff", R.drawable.bus)
                604u -> Line("124", "Victoria", "#009ee0", "#ffffff", R.drawable.bus)
                605u -> Line("125", "Ontario", "#009ee0", "#ffffff", R.drawable.bus)
                606u -> Line("126", "Thimens / Grenet", "#009ee0", "#ffffff", R.drawable.bus)
                607u -> Line("128", "Saint-Laurent", "#009ee0", "#ffffff", R.drawable.bus)
                608u -> Line("129", "Côte-Sainte-Catherine", "#009ee0", "#ffffff", R.drawable.bus)
                609u -> Line("131", "De l'Assomption", "#009ee0", "#ffffff", R.drawable.bus)
                610u -> Line("135", "De l'Esplanade", "#009ee0", "#ffffff", R.drawable.bus)
                611u -> Line("136", "Viau", "#781b7d", "#ffffff", R.drawable.bus)
                612u -> Line("138", "Notre-Dame-de-Grâce", "#009ee0", "#ffffff", R.drawable.bus)
                613u -> Line("139", "Pie-IX", "#009ee0", "#ffffff", R.drawable.bus)
                614u -> Line("140", "Fleury", "#009ee0", "#ffffff", R.drawable.bus)
                615u -> Line("141", "Jean-Talon Est", "#781b7d", "#ffffff", R.drawable.bus)
                616u -> Line("144", "Avenue des Pins", "#009ee0", "#ffffff", R.drawable.bus)
                617u -> Line("146", "Christophe-Colomb / Meilleur", "#009ee0", "#ffffff", R.drawable.bus)
                618u -> Line("150", "René-Lévesque", "#009ee0", "#ffffff", R.drawable.bus)
                619u -> Line("160", "Barclay", "#009ee0", "#ffffff", R.drawable.bus)
                620u -> Line("161", "Van Horne", "#781b7d", "#ffffff", R.drawable.bus)
                621u -> Line("162", "Westminster", "#009ee0", "#ffffff", R.drawable.bus)
                622u -> Line("164", "Dudemaine", "#009ee0", "#ffffff", R.drawable.bus)
                623u -> Line("165", "Côte-des-Neiges", "#781b7d", "#ffffff", R.drawable.bus)
                624u -> Line("166", "Queen-Mary", "#009ee0", "#ffffff", R.drawable.bus)
                625u -> Line("168", "Cité-du-Havre", "#009ee0", "#ffffff", R.drawable.bus)
                626u -> Line("170", "Keller", "#009ee0", "#ffffff", R.drawable.bus)
                627u -> Line("171", "Henri-Bourassa", "#781b7d", "#ffffff", R.drawable.bus)
                628u -> Line("172", "Du Golf", "#009ee0", "#ffffff", R.drawable.bus)
                629u -> Line("174", "Côte-Vertu-Ouest", "#009ee0", "#ffffff", R.drawable.bus)
                630u -> Line("175", "Griffith / Saint-François", "#009ee0", "#ffffff", R.drawable.bus)
                631u -> Line("176", "Berlioz", "#009ee0", "#ffffff", R.drawable.bus)
                632u -> Line("177", "Thimens", "#009ee0", "#ffffff", R.drawable.bus)
                633u -> Line("178", "Pointe-Nord / Île-des-Soeurs", "#009ee0", "#ffffff", R.drawable.bus)
                634u -> Line("179", "De l'Acadie", "#009ee0", "#ffffff", R.drawable.bus)
                635u -> Line("180", "De Salaberry", "#009ee0", "#ffffff", R.drawable.bus)
                636u -> Line("183", "Gouin Est", "#009ee0", "#ffffff", R.drawable.bus)
                637u -> Line("185", "Sherbrooke", "#009ee0", "#ffffff", R.drawable.bus)
                638u -> Line("186", "Sherbrooke-Est", "#009ee0", "#ffffff", R.drawable.bus)
                639u -> Line("187", "René-Lévesque", "#781b7d", "#ffffff", R.drawable.bus)
                640u -> Line("188", "Couture", "#009ee0", "#ffffff", R.drawable.bus)
                641u -> Line("189", "Notre-Dame", "#009ee0", "#ffffff", R.drawable.bus)
                642u -> Line("191", "Broadway / Provost", "#009ee0", "#ffffff", R.drawable.bus)
                643u -> Line("192", "Robert", "#009ee0", "#ffffff", R.drawable.bus)
                644u -> Line("193", "Jarry", "#781b7d", "#ffffff", R.drawable.bus)
                645u -> Line("195", "Sherbrooke / Notre-Dame", "#009ee0", "#ffffff", R.drawable.bus)
                646u -> Line("196", "Parc-Industriel-Lachine", "#781b7d", "#ffffff", R.drawable.bus)
                647u -> Line("197", "Rosemont", "#781b7d", "#ffffff", R.drawable.bus)
                648u -> Line("200", "Sainte-Anne-de-Bellevue", "#009ee0", "#ffffff", R.drawable.bus)
                649u -> Line("201", "Saint-Charles / Saint-Jean", "#009ee0", "#ffffff", R.drawable.bus)
                650u -> Line("202", "Dawson", "#009ee0", "#ffffff", R.drawable.bus)
                651u -> Line("203", "Carson", "#009ee0", "#ffffff", R.drawable.bus)
                652u -> Line("204", "Cardinal", "#009ee0", "#ffffff", R.drawable.bus)
                653u -> Line("205", "Gouin", "#009ee0", "#ffffff", R.drawable.bus)
                654u -> Line("206", "Roger-Pilon", "#009ee0", "#ffffff", R.drawable.bus)
                655u -> Line("207", "Jacques-Bizard", "#009ee0", "#ffffff", R.drawable.bus)
                656u -> Line("208", "Brunswick", "#009ee0", "#ffffff", R.drawable.bus)
                657u -> Line("209", "Des Sources", "#009ee0", "#ffffff", R.drawable.bus)
                658u -> Line("211", "Bord-du-Lac", "#009ee0", "#ffffff", R.drawable.bus)
                659u -> Line("212", "Sainte-Anne", "#009ee0", "#ffffff", R.drawable.bus)
                660u -> Line("213", "Parc-Industriel-Saint-Laurent", "#009ee0", "#ffffff", R.drawable.bus)
                661u -> Line("215", "Henri-Bourassa", "#009ee0", "#ffffff", R.drawable.bus)
                662u -> Line("216", "Transcanadienne", "#009ee0", "#ffffff", R.drawable.bus)
                663u -> Line("217", "Anse-à-l'Orme", "#009ee0", "#ffffff", R.drawable.bus)
                664u -> Line("218", "Antoine-Faucon", "#009ee0", "#ffffff", R.drawable.bus)
                665u -> Line("219", "Chemin Sainte-Marie", "#009ee0", "#ffffff", R.drawable.bus)
                666u -> Line("220", "Kieran", "#009ee0", "#ffffff", R.drawable.bus)
                667u -> Line("225", "Hymus", "#009ee0", "#ffffff", R.drawable.bus)
                668u -> Line("350", "Verdun / LaSalle", "#000000", "#ffffff", R.drawable.bus)
                669u -> Line("353", "Lacordaire / Maurice-Duplessis", "#000000", "#ffffff", R.drawable.bus)
                670u -> Line("354", "Sainte-Anne-de-Bellevue / Centre-ville", "#000000", "#ffffff", R.drawable.bus)
                671u -> Line("355", "Pie-IX", "#000000", "#ffffff", R.drawable.bus)
                672u -> Line("356", "Lachine / YUL Aéroport / Des Sources", "#000000", "#ffffff", R.drawable.bus)
                673u -> Line("357", "Saint-Michel", "#000000", "#ffffff", R.drawable.bus)
                674u -> Line("358", "Sainte-Catherine", "#000000", "#ffffff", R.drawable.bus)
                675u -> Line("359", "Papineau", "#000000", "#ffffff", R.drawable.bus)
                676u -> Line("360", "Avenue des Pins", "#000000", "#ffffff", R.drawable.bus)
                677u -> Line("361", "Saint-Denis", "#000000", "#ffffff", R.drawable.bus)
                678u -> Line("362", "Hochelaga / Notre-Dame", "#000000", "#ffffff", R.drawable.bus)
                679u -> Line("363", "Boulevard Saint-Laurent", "#000000", "#ffffff", R.drawable.bus)
                680u -> Line("364", "Sherbrooke / Joseph-Renaud", "#000000", "#ffffff", R.drawable.bus)
                681u -> Line("365", "Avenue du Parc", "#000000", "#ffffff", R.drawable.bus)
                682u -> Line("368", "Avenue-du-Mont-Royal", "#000000", "#ffffff", R.drawable.bus)
                683u -> Line("369", "Côte-des-Neiges", "#000000", "#ffffff", R.drawable.bus)
                684u -> Line("370", "Rosemont", "#000000", "#ffffff", R.drawable.bus)
                685u -> Line("371", "Décarie", "#000000", "#ffffff", R.drawable.bus)
                686u -> Line("372", "Jean-Talon", "#000000", "#ffffff", R.drawable.bus)
                687u -> Line("376", "Pierrefonds / Centre-ville", "#000000", "#ffffff", R.drawable.bus)
                688u -> Line("378", "Sauvé / YUL Aéroport", "#000000", "#ffffff", R.drawable.bus)
                689u -> Line("380", "Henri-Bourassa", "#000000", "#ffffff", R.drawable.bus)
                690u -> Line("382", "Pierrefonds / Saint-Charles", "#000000", "#ffffff", R.drawable.bus)
                691u -> Line("401", "Express Saint-Charles", "#009ee0", "#ffffff", R.drawable.bus)
                692u -> Line("405", "Express Bord-du-Lac", "#009ee0", "#ffffff", R.drawable.bus)
                693u -> Line("406", "Express Newman", "#781b7d", "#ffffff", R.drawable.bus)
                694u -> Line("407", "Express Île-Bizard", "#009ee0", "#ffffff", R.drawable.bus)
                695u -> Line("409", "Express Des Sources", "#009ee0", "#ffffff", R.drawable.bus)
                696u -> Line("410", "Express Notre-Dame", "#009ee0", "#ffffff", R.drawable.bus)
                697u -> Line("411", "Express Lionel-Groulx", "#009ee0", "#ffffff", R.drawable.bus)
                698u -> Line("419", "Express John Abbott", "#009ee0", "#ffffff", R.drawable.bus)
                699u -> Line("420", "Express Notre-Dame-de-Grâce", "#009ee0", "#ffffff", R.drawable.bus)
                700u -> Line("425", "Express Anse-à-l'Orme", "#009ee0", "#ffffff", R.drawable.bus)
                701u -> Line("427", "Express Saint-Joseph", "#009ee0", "#ffffff", R.drawable.bus)
                702u -> Line("428", "Express Parcs industriels de l'Est", "#009ee0", "#ffffff", R.drawable.bus)
                703u -> Line("430", "Express Pointe-aux-Trembles", "#009ee0", "#ffffff", R.drawable.bus)
                704u -> Line("432", "Express Lacordaire", "#009ee0", "#ffffff", R.drawable.bus)
                705u -> Line("439", "Express Pie-IX", "#781b7d", "#ffffff", R.drawable.bus)
                706u -> Line("440", "Express Charleroi", "#009ee0", "#ffffff", R.drawable.bus)
                707u -> Line("444", "Express Cégep Marie-Victorin", "#009ee0", "#ffffff", R.drawable.bus)
                708u -> Line("445", "Express Papineau", "#009ee0", "#ffffff", R.drawable.bus)
                709u -> Line("448", "Express Maurice-Duplessis", "#009ee0", "#ffffff", R.drawable.bus)
                710u -> Line("449", "Express Rivière-des-Prairies", "#009ee0", "#ffffff", R.drawable.bus)
                711u -> Line("460", "Express Métropolitaine", "#009ee0", "#ffffff", R.drawable.bus)
                712u -> Line("465", "Express Côte-des-Neiges", "#009ee0", "#ffffff", R.drawable.bus)
                713u -> Line("467", "Express Saint-Michel", "#009ee0", "#ffffff", R.drawable.bus)
                714u -> Line("468", "Express Pierrefonds / Gouin", "#009ee0", "#ffffff", R.drawable.bus)
                715u -> Line("469", "Express Henri-Bourassa", "#009ee0", "#ffffff", R.drawable.bus)
                716u -> Line("470", "Express Pierrefonds", "#781b7d", "#ffffff", R.drawable.bus)
                717u -> Line("475", "Express Dollard-des-Ormeaux", "#009ee0", "#ffffff", R.drawable.bus)
                718u -> Line("480", "Express du Parc", "#009ee0", "#ffffff", R.drawable.bus)
                719u -> Line("485", "Express Antoine-Faucon", "#009ee0", "#ffffff", R.drawable.bus)
                720u -> Line("486", "Express Sherbrooke", "#009ee0", "#ffffff", R.drawable.bus)
                721u -> Line("487", "Express Bout-de-l'Île", "#009ee0", "#ffffff", R.drawable.bus)
                722u -> Line("491", "Express Lachine", "#009ee0", "#ffffff", R.drawable.bus)
                723u -> Line("495", "Express Lachine / LaSalle", "#009ee0", "#ffffff", R.drawable.bus)
                724u -> Line("496", "Express Victoria", "#009ee0", "#ffffff", R.drawable.bus)
                725u -> Line("711", "Parc-du-Mont-Royal / Oratoire", "#009ee0", "#ffffff", R.drawable.bus)
                726u -> Line("715", "Vieux-Montréal / Vieux-Port", "#009ee0", "#ffffff", R.drawable.bus)
                727u -> Line("747", "YUL Aéroport  / Centre-Ville", "#009ee0", "#ffffff", R.drawable.bus)
                728u -> Line("767", "La Ronde / Station Jean-Drapeau", "#009ee0", "#ffffff", R.drawable.bus)
                729u -> Line("768", "Plage Jean-Doré / Station Jean-Drapeau", "#009ee0", "#ffffff", R.drawable.bus)
                730u -> Line("769", "La Ronde / Station Papineau", "#009ee0", "#ffffff", R.drawable.bus)
                731u -> Line("777", "Jean-Drapeau / Casino / Bonaventure", "#009ee0", "#ffffff", R.drawable.bus)
                732u -> Line("811", "Navette Services santé", "#009ee0", "#ffffff", R.drawable.bus)
                733u -> Line("822", "Navette Longue-Pointe", "#009ee0", "#ffffff", R.drawable.bus)
                734u -> Line("968", "Trainbus Roxboro / Côte-Vertu", "#009ee0", "#ffffff", R.drawable.bus)
                else -> Line("", "STM Unknown ($id)", "#009ee0", "#ffffff", R.drawable.bus)
            }
        }

        private fun getRTLLineById(id: UInt): Line {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> Line("1", "Desaulniers / Victoria / Windsor", "#9e2536", "#ffffff", R.drawable.bus)
                514u -> Line("3", "Secteur Laflèche", "#9e2536", "#ffffff", R.drawable.bus)
                515u -> Line("4", "Taschereau / Payer / DIX30", "#9e2536", "#ffffff", R.drawable.bus)
                516u -> Line("5", "Auteuil / Mtée St-Hubert / Maisonneuve", "#9e2536", "#ffffff", R.drawable.bus)
                517u -> Line("6", "Victoria", "#9e2536", "#ffffff", R.drawable.bus)
                518u -> Line("8", "Ch. Chambly / Cousineau / Promenades St-Bruno", "#9e2536", "#ffffff", R.drawable.bus)
                519u -> Line("9", "Secteurs L-M St-Hubert", "#9e2536", "#ffffff", R.drawable.bus)
                520u -> Line("10", "Roland-Therrien / Belcourt", "#9e2536", "#ffffff", R.drawable.bus)
                521u -> Line("13", "Riverside / Secteurs P-V Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                522u -> Line("14", "Rome / DIX30", "#9e2536", "#ffffff", R.drawable.bus)
                523u -> Line("15", "Riverside / Alexandra / Churchill", "#9e2536", "#ffffff", R.drawable.bus)
                524u -> Line("16", "Nobert / King-George / Adoncour", "#9e2536", "#ffffff", R.drawable.bus)
                525u -> Line("17", "Roland-Therrien / Roberval", "#9e2536", "#ffffff", R.drawable.bus)
                526u -> Line("19", "Davis", "#9e2536", "#ffffff", R.drawable.bus)
                527u -> Line("20", "Jean-Paul-Vincent / Beauharnois", "#9e2536", "#ffffff", R.drawable.bus)
                528u -> Line("21", "Grande-Allée / du Quartier", "#9e2536", "#ffffff", R.drawable.bus)
                529u -> Line("22", "Gare Longueuil - St-Hubert / Sect. B Vieux-Longueuil", "#9e2536", "#ffffff", R.drawable.bus)
                530u -> Line("23", "Ste-Hélène / Jacques-Cartier", "#9e2536", "#ffffff", R.drawable.bus)
                531u -> Line("25", "Parcs industriels Vieux-Longueuil / Boucherville", "#9e2536", "#ffffff", R.drawable.bus)
                532u -> Line("28", "Ch. Chambly / Savane / ENA", "#9e2536", "#ffffff", R.drawable.bus)
                533u -> Line("29", "Collectivité Nouvelle", "#9e2536", "#ffffff", R.drawable.bus)
                534u -> Line("30", "Secteurs P-V Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                535u -> Line("31", "Secteurs R-S-T Brossard / St-Laurent", "#9e2536", "#ffffff", R.drawable.bus)
                536u -> Line("32", "Secteur B Brossard / Mountainview", "#9e2536", "#ffffff", R.drawable.bus)
                537u -> Line("33", "Secteurs M-N-O Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                538u -> Line("34", "Secteur A Brossard / Bellevue", "#9e2536", "#ffffff", R.drawable.bus)
                539u -> Line("37", "Simard / du Béarn", "#9e2536", "#ffffff", R.drawable.bus)
                540u -> Line("38", "Chevrier / Secteur B Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                541u -> Line("41", "Rome / Milan", "#9e2536", "#ffffff", R.drawable.bus)
                542u -> Line("42", "Gaétan-Boucher / Parc de la Cité", "#9e2536", "#ffffff", R.drawable.bus)
                543u -> Line("43", "Milan / Rome", "#9e2536", "#ffffff", R.drawable.bus)
                544u -> Line("44", "Secteurs M-N-O Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                545u -> Line("46", "Secteurs R-S-T Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                546u -> Line("47", "Secteurs R-S-T Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                547u -> Line("49", "Secteurs R-S Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                548u -> Line("50", "Bienville / Orchard / Prince-Charles", "#9e2536", "#ffffff", R.drawable.bus)
                549u -> Line("54", "Tiffin / St-Georges / Taschereau", "#9e2536", "#ffffff", R.drawable.bus)
                550u -> Line("55", "Victoria / Wellington", "#9e2536", "#ffffff", R.drawable.bus)
                551u -> Line("59", "Montgomery / Gareau", "#9e2536", "#ffffff", R.drawable.bus)
                552u -> Line("60", "Milan / Gaétan-Boucher / Promenades St-Bruno", "#9e2536", "#ffffff", R.drawable.bus)
                553u -> Line("61", "Boucherville / Station Radisson", "#9e2536", "#ffffff", R.drawable.bus)
                554u -> Line("71", "Curé-Poirier", "#9e2536", "#ffffff", R.drawable.bus)
                555u -> Line("73", "Joliette / de Lyon", "#9e2536", "#ffffff", R.drawable.bus)
                556u -> Line("74", "St-Laurent / Secteur Bellerive", "#9e2536", "#ffffff", R.drawable.bus)
                557u -> Line("75", "Quinn / Brébeuf", "#9e2536", "#ffffff", R.drawable.bus)
                558u -> Line("76", "Roland-Therrien / Roberval", "#9e2536", "#ffffff", R.drawable.bus)
                559u -> Line("77", "Taschereau / Coteau-Rouge / Cégep É.-Montpetit", "#9e2536", "#ffffff", R.drawable.bus)
                560u -> Line("78", "Adoncour / du Colisée", "#9e2536", "#ffffff", R.drawable.bus)
                561u -> Line("80", "De Montarville / Carrefour de la Rive-Sud", "#9e2536", "#ffffff", R.drawable.bus)
                562u -> Line("81", "du Fort-St-Louis / Marie-Victorin", "#9e2536", "#ffffff", R.drawable.bus)
                563u -> Line("82", "Marie-Victorin / du Fort-St-Louis", "#9e2536", "#ffffff", R.drawable.bus)
                564u -> Line("83", "De Montarville / Samuel-De Champlain", "#9e2536", "#ffffff", R.drawable.bus)
                565u -> Line("84", "Samuel-De Champlain / De Montarville", "#9e2536", "#ffffff", R.drawable.bus)
                566u -> Line("85", "Îles-Percées / de Mortagne / de Gascogne", "#9e2536", "#ffffff", R.drawable.bus)
                567u -> Line("86", "Samuel-De Champlain / De Montarville / TCV", "#9e2536", "#ffffff", R.drawable.bus)
                568u -> Line("87", "Marie-Victorin / du Fort St-Louis / TCV", "#9e2536", "#ffffff", R.drawable.bus)
                569u -> Line("88", "Ch. Chambly / Mountainview", "#9e2536", "#ffffff", R.drawable.bus)
                570u -> Line("93", "Gare St-Bruno / Montarville / Y.-Duckett", "#9e2536", "#ffffff", R.drawable.bus)
                571u -> Line("98", "Parc industriel St-Bruno / Parent", "#9e2536", "#ffffff", R.drawable.bus)
                572u -> Line("99", "Promenades St-Bruno / Saint-Bruno-de-Montarville", "#9e2536", "#ffffff", R.drawable.bus)
                573u -> Line("120", "Fernand-Lafontaine / Stationnement de Mortagne", "#9e2536", "#ffffff", R.drawable.bus)
                574u -> Line("123", "Jacques-Cartier / Parcs industriels", "#9e2536", "#ffffff", R.drawable.bus)
                575u -> Line("125", "Pratt & Whitney / Lumenpulse", "#9e2536", "#ffffff", R.drawable.bus)
                576u -> Line("128", "Zone aéroportuaire / Parc industriel St-Bruno", "#9e2536", "#ffffff", R.drawable.bus)
                577u -> Line("132", "DIX30 / Parc de la Cité / Mountainview", "#9e2536", "#ffffff", R.drawable.bus)
                578u -> Line("160", "Milan / Gaétan-Boucher / Centre-ville St-Bruno", "#9e2536", "#ffffff", R.drawable.bus)
                579u -> Line("161", "R.-Therrien / J.-Cartier / De Montarville", "#9e2536", "#ffffff", R.drawable.bus)
                580u -> Line("170", "Station Papineau / Ste-Hélène / J.-Cartier", "#9e2536", "#ffffff", R.drawable.bus)
                581u -> Line("180", "De Montarville / des Sureaux", "#9e2536", "#ffffff", R.drawable.bus)
                582u -> Line("185", "Ampère / Gay-Lussac", "#9e2536", "#ffffff", R.drawable.bus)
                583u -> Line("192", "Station Brossard / Montarville / Y.-Duckett", "#9e2536", "#ffffff", R.drawable.bus)
                584u -> Line("199", "Seigneurial / Grand Boulevard", "#9e2536", "#ffffff", R.drawable.bus)
                585u -> Line("214", "Station Brossard / de Rome / St-Laurent", "#9e2536", "#ffffff", R.drawable.bus)
                586u -> Line("284", "Navette Boucherville", "#9e2536", "#ffffff", R.drawable.bus)
                587u -> Line("410", "Express Roland-Therrien / Belcourt", "#9e2536", "#ffffff", R.drawable.bus)
                588u -> Line("417", "Express Roland-Therrien / Roberval", "#9e2536", "#ffffff", R.drawable.bus)
                589u -> Line("421", "Grande-Allée / A.-Frappier", "#9e2536", "#ffffff", R.drawable.bus)
                590u -> Line("428", "Zone aéroportuaire / Agence Spatiale canadienne", "#9e2536", "#ffffff", R.drawable.bus)
                591u -> Line("442", "Cousineau / Pacific", "#9e2536", "#ffffff", R.drawable.bus)
                592u -> Line("461", "Express de Touraine / de Montarville / Radisson", "#9e2536", "#ffffff", R.drawable.bus)
                593u -> Line("462", "Touraine-Mortagne-Radisson-HMR-Inst.cardio", "#9e2536", "#ffffff", R.drawable.bus)
                594u -> Line("500", "École Saint-Lambert International High School", "#9e2536", "#ffffff", R.drawable.bus)
                595u -> Line("503", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                596u -> Line("505", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                597u -> Line("521", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                598u -> Line("524", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                599u -> Line("525", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                600u -> Line("526", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                601u -> Line("530", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                602u -> Line("532", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                603u -> Line("533", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                604u -> Line("534", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                605u -> Line("535", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                606u -> Line("536", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                607u -> Line("538", "École Heritage Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                608u -> Line("539", "École Heritage Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                609u -> Line("540", "École Heritage Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                610u -> Line("542", "École Heritage Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                611u -> Line("544", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                612u -> Line("546", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                613u -> Line("547", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                614u -> Line("549", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                615u -> Line("550", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                616u -> Line("551", "École Centennial Regional High School", "#9e2536", "#ffffff", R.drawable.bus)
                617u -> Line("565", "École Saint-Lambert International High School", "#9e2536", "#ffffff", R.drawable.bus)
                618u -> Line("570", "École Saint-Lambert International High School", "#9e2536", "#ffffff", R.drawable.bus)
                619u -> Line("572", "École Saint-Lambert International High School", "#9e2536", "#ffffff", R.drawable.bus)
                620u -> Line("575", "École Saint-Lambert International High School", "#9e2536", "#ffffff", R.drawable.bus)
                621u -> Line("580", "École Saint-Lambert International High School", "#9e2536", "#ffffff", R.drawable.bus)
                622u -> Line("600", "Écoles privées", "#9e2536", "#ffffff", R.drawable.bus)
                623u -> Line("601", "École de l'Agora", "#9e2536", "#ffffff", R.drawable.bus)
                624u -> Line("602", "École de l'Agora", "#9e2536", "#ffffff", R.drawable.bus)
                625u -> Line("604", "École de l'Agora", "#9e2536", "#ffffff", R.drawable.bus)
                626u -> Line("605", "École de l'Agora", "#9e2536", "#ffffff", R.drawable.bus)
                627u -> Line("606", "Écoles privées", "#9e2536", "#ffffff", R.drawable.bus)
                628u -> Line("607", "École de l'Agora", "#9e2536", "#ffffff", R.drawable.bus)
                629u -> Line("608", "École André-Laurendeau et Cégep Édouard-Montpetit", "#9e2536", "#ffffff", R.drawable.bus)
                630u -> Line("609", "École de l'Agora", "#9e2536", "#ffffff", R.drawable.bus)
                631u -> Line("613", "Écoles privées", "#9e2536", "#ffffff", R.drawable.bus)
                632u -> Line("614", "Écoles privées", "#9e2536", "#ffffff", R.drawable.bus)
                633u -> Line("616", "École Gérard-Filion", "#9e2536", "#ffffff", R.drawable.bus)
                634u -> Line("618", "Écoles privées", "#9e2536", "#ffffff", R.drawable.bus)
                635u -> Line("620", "Collège Français", "#9e2536", "#ffffff", R.drawable.bus)
                636u -> Line("624", "École St-Jean-Baptiste", "#9e2536", "#ffffff", R.drawable.bus)
                637u -> Line("640", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                638u -> Line("644", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                639u -> Line("650", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                640u -> Line("653", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                641u -> Line("656", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                642u -> Line("660", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                643u -> Line("664", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                644u -> Line("665", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                645u -> Line("670", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                646u -> Line("671", "École Jacques-Rousseau", "#9e2536", "#ffffff", R.drawable.bus)
                647u -> Line("672", "École Jacques-Rousseau", "#9e2536", "#ffffff", R.drawable.bus)
                648u -> Line("673", "École Jacques-Rousseau", "#9e2536", "#ffffff", R.drawable.bus)
                649u -> Line("674", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                650u -> Line("675", "École Jacques-Rousseau", "#9e2536", "#ffffff", R.drawable.bus)
                651u -> Line("676", "École Jacques-Rousseau", "#9e2536", "#ffffff", R.drawable.bus)
                652u -> Line("678", "École Jacques-Rousseau", "#9e2536", "#ffffff", R.drawable.bus)
                653u -> Line("683", "Cégep Édouard-Montpetit", "#9e2536", "#ffffff", R.drawable.bus)
                654u -> Line("684", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                655u -> Line("689", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                656u -> Line("690", "École Antoine-Brossard", "#9e2536", "#ffffff", R.drawable.bus)
                657u -> Line("691", "École Lucille-Teasdale", "#9e2536", "#ffffff", R.drawable.bus)
                658u -> Line("692", "École Lucille-Teasdale", "#9e2536", "#ffffff", R.drawable.bus)
                659u -> Line("693", "École Lucille-Teasdale", "#9e2536", "#ffffff", R.drawable.bus)
                660u -> Line("694", "École Lucille-Teasdale", "#9e2536", "#ffffff", R.drawable.bus)
                661u -> Line("695", "École Lucille-Teasdale", "#9e2536", "#ffffff", R.drawable.bus)
                662u -> Line("696", "École Lucille-Teasdale", "#9e2536", "#ffffff", R.drawable.bus)
                663u -> Line("697", "École Lucille-Teasdale - Secteur Chevrier", "#9e2536", "#ffffff", R.drawable.bus)
                else -> Line("", "RTL Unknown ($id)", "#9e2536", "#ffffff", R.drawable.bus)
            }
        }

        private fun getEXOLineById(id: UInt): Line {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> Line("11", "Vaudreuil-Hudson", "#f16179", "#ffffff", R.drawable.train)
                514u -> Line("12", "Saint-Jérôme", "#fed16d", "#ffffff", R.drawable.train)
                515u -> Line("13", "Mont-Saint-Hilaire", "#999ac6", "#ffffff", R.drawable.train)
                516u -> Line("14", "Candiac", "#5ab6b2", "#ffffff", R.drawable.train)
                517u -> Line("15", "Mascouche", "#ca5898", "#ffffff", R.drawable.train)
                518u -> Line("12", "Saint-Jérôme (zone B)", "#fed16d", "#ffffff", R.drawable.train)
                519u -> Line("13", "Mont-Saint-Hilaire (zone B)", "#999ac6", "#ffffff", R.drawable.train)
                520u -> Line("11", "Vaudreuil-Hudson (zone C)", "#f16179", "#ffffff", R.drawable.train)
                521u -> Line("12", "Saint-Jérôme (zone C)", "#fed16d", "#ffffff", R.drawable.train)
                522u -> Line("13", "Mont-Saint-Hilaire (zone C)", "#999ac6", "#ffffff", R.drawable.train)
                523u -> Line("14", "Candiac (zone C)", "#5ab6b2", "#ffffff", R.drawable.train)
                524u -> Line("15", "Mascouche (zone C)", "#ca5898", "#ffffff", R.drawable.train)
                else -> Line("", "EXO Unknown ($id)", "#000000", "#ffffff", R.drawable.train)
            }
        }

        private fun getRTCLineById(id: UInt): Line {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> Line("1", "Station Belvédère - Gare fluviale / Cap-Blanc", "#003878", "#ffffff", R.drawable.bus)
                514u -> Line("107", "Gare du Palais - Pointe-de-Sainte-Foy", "#003878", "#ffffff", R.drawable.bus)
                515u -> Line("11", "Gare fluviale - Pointe-de-Sainte-Foy", "#003878", "#ffffff", R.drawable.bus)
                516u -> Line("11G", "C.-Laforte / McCartney", "#003878", "#ffffff", R.drawable.bus)
                517u -> Line("13", "Saint-Louis/Sainte-Foy Centre/du Versant-Nord - Du Versant-Nord/Sainte-Foy Centre/Saint-Louis", "#003878", "#ffffff", R.drawable.bus)
                518u -> Line("133", "Vieux-Québec - Terminus de la Faune", "#003878", "#ffffff", R.drawable.bus)
                519u -> Line("136", "Colline Parlementaire - Montagne-des-Roches", "#003878", "#ffffff", R.drawable.bus)
                520u -> Line("13A", "École secondaire De Rochebelle - De Terrebonne / de La Suète", "#003878", "#ffffff", R.drawable.bus)
                521u -> Line("13B", "École secondaire De Rochebelle - Des Sapins / du Versant-Nord", "#003878", "#ffffff", R.drawable.bus)
                522u -> Line("14", "Pointe-de-Sainte-Foy - Cap-Rouge", "#003878", "#ffffff", R.drawable.bus)
                523u -> Line("14A", "Collège des Compagnons - De la Rivière / du Domaine", "#003878", "#ffffff", R.drawable.bus)
                524u -> Line("14G", "Collège Jésus-Marie de Sillery - Des Carougeois / J.-C.-Cantin", "#003878", "#ffffff", R.drawable.bus)
                525u -> Line("15", "Pointe-de-Sainte-Foy - Cap-Rouge", "#003878", "#ffffff", R.drawable.bus)
                526u -> Line("15A", "Collège des Compagnons - de la Prom.-des-Soeurs / J.-C.-Cantin", "#003878", "#ffffff", R.drawable.bus)
                527u -> Line("15B", "Collège des Compagnons - de la Prom-des-Soeurs / Escoffier", "#003878", "#ffffff", R.drawable.bus)
                528u -> Line("16", "Sillery / U. Laval / Sainte-Foy Centre - U. Laval / Sillery / Sainte-Foy Centre", "#003878", "#ffffff", R.drawable.bus)
                529u -> Line("18", "Gare du Palais - Université Laval", "#003878", "#ffffff", R.drawable.bus)
                530u -> Line("185", "Station Belvédère / Sainte-Foy Centre - Neufchâtel", "#003878", "#ffffff", R.drawable.bus)
                531u -> Line("19", "Grand Théâtre - Limoilou", "#003878", "#ffffff", R.drawable.bus)
                532u -> Line("214", "Gare du Palais - Cap-Rouge", "#003878", "#ffffff", R.drawable.bus)
                533u -> Line("215", "Gare du Palais - Cap-Rouge", "#003878", "#ffffff", R.drawable.bus)
                534u -> Line("22", "Sainte-Foy Centre - Terminus Les Saules", "#003878", "#ffffff", R.drawable.bus)
                535u -> Line("230", "Colline Parlementaire - Terminus de la Faune", "#003878", "#ffffff", R.drawable.bus)
                536u -> Line("236", "Colline Parlementaire - Station des Roses", "#003878", "#ffffff", R.drawable.bus)
                537u -> Line("238", "Colline Parlementaire - Guillaume-Mathieu", "#003878", "#ffffff", R.drawable.bus)
                538u -> Line("239", "Colline Parlementaire - Terminus de la Faune", "#003878", "#ffffff", R.drawable.bus)
                539u -> Line("25", "Place D'Youville / Gare du Palais - Pointe-de-Sainte-Foy", "#003878", "#ffffff", R.drawable.bus)
                540u -> Line("250", "Colline Parlementaire - Terminus Chute-Montmorency", "#003878", "#ffffff", R.drawable.bus)
                541u -> Line("251", "Colline Parlementaire - Parc-O-Bus Sainte-Anne", "#003878", "#ffffff", R.drawable.bus)
                542u -> Line("253", "Colline Parlementaire - Courville", "#003878", "#ffffff", R.drawable.bus)
                543u -> Line("254", "Colline Parlementaire - Sainte-Thérèse-de-Lisieux", "#003878", "#ffffff", R.drawable.bus)
                544u -> Line("255", "Colline Parlementaire - Sainte-Thérèse-de-Lisieux", "#003878", "#ffffff", R.drawable.bus)
                545u -> Line("257", "Colline Parlementaire - Sainte-Thérèse-de-Lisieux", "#003878", "#ffffff", R.drawable.bus)
                546u -> Line("258", "Colline Parlementaire - Sainte-Thérèse-de-Lisieux", "#003878", "#ffffff", R.drawable.bus)
                547u -> Line("25G", "Pointe-de-Sainte-Foy", "#003878", "#ffffff", R.drawable.bus)
                548u -> Line("272", "Colline Parlementaire - Loretteville", "#003878", "#ffffff", R.drawable.bus)
                549u -> Line("273", "Colline Parlementaire - Loretteville Sud", "#003878", "#ffffff", R.drawable.bus)
                550u -> Line("274", "Colline Parlementaire - Neufchâtel", "#003878", "#ffffff", R.drawable.bus)
                551u -> Line("277", "Colline Parlementaire - Val-Bélair", "#003878", "#ffffff", R.drawable.bus)
                552u -> Line("279", "Colline Parlementaire - L'Ancienne-Lorette", "#003878", "#ffffff", R.drawable.bus)
                553u -> Line("28", "Colline Parlementaire - 51e Rue Est", "#003878", "#ffffff", R.drawable.bus)
                554u -> Line("280", "Place Jacques-Cartier / colline Parlementaire - L'Ancienne-Lorette", "#003878", "#ffffff", R.drawable.bus)
                555u -> Line("281", "Colline Parlementaire - Neufchâtel", "#003878", "#ffffff", R.drawable.bus)
                556u -> Line("282", "Colline Parlementaire - Lac-Saint-Charles", "#003878", "#ffffff", R.drawable.bus)
                557u -> Line("283", "Gare du Palais - Champigny", "#003878", "#ffffff", R.drawable.bus)
                558u -> Line("284", "Colline Parlementaire - Loretteville", "#003878", "#ffffff", R.drawable.bus)
                559u -> Line("289", "Colline Parlementaire - Saint-Émile", "#003878", "#ffffff", R.drawable.bus)
                560u -> Line("29", "Parc Colbert Ouest - Place Jacques-Cartier", "#003878", "#ffffff", R.drawable.bus)
                561u -> Line("290", "Vieux-Québec - Loretteville", "#003878", "#ffffff", R.drawable.bus)
                562u -> Line("292", "Place Jacques-Cartier - Saint-Augustin", "#003878", "#ffffff", R.drawable.bus)
                else -> Line("", "RTC Unknown ($id)", "#003878", "#ffffff", R.drawable.bus)
            }
        }

        private fun getSTLLineById(id: UInt): Line {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> Line("12", "Pont-Viau / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                514u -> Line("144", "Métro Côte-Vertu / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus)
                515u -> Line("151", "Sainte-Rose / Métro Côte-Vertu", "#151f6d", "#ffffff", R.drawable.bus)
                302u -> Line("16", "Métro Montmorency / Laval-des-Rapides / Armand-Frappier", "#151f6d", "#ffffff", R.drawable.bus)
                3u -> Line("17", "Auteuil / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                518u -> Line("2", "Métro Henri-Bourassa / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
                519u -> Line("20", "Métro Cartier / Chomedey", "#151f6d", "#ffffff", R.drawable.bus)
                520u -> Line("22", "Saint-François / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                190u -> Line("222", "Saint-Vincent-De-Paul / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                522u -> Line("24", "Métro Cartier / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus)
                150u -> Line("252", "Saint-François / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus)
                524u -> Line("26", "Métro Montmorency / Gare Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus)
                8u -> Line("27", "Gare Vimont / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                10u -> Line("31", "Auteuil / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus)
                527u -> Line("313", "Chomedey / Métro Côte-Vertu", "#151f6d", "#ffffff", R.drawable.bus)
                528u -> Line("33", "Métro Montmorency / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                529u -> Line("345", "Gare Vimont / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus)
                530u -> Line("36", "Métro Montmorency / Chomedey", "#151f6d", "#ffffff", R.drawable.bus)
                531u -> Line("360", "Navette Centre-Ville (Gratuit)", "#151f6d", "#ffffff", R.drawable.bus)
                532u -> Line("37", "Sainte-Rose / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                13u -> Line("39", "Auteuil / Terminus Le Carrefour", "#151f6d", "#ffffff", R.drawable.bus)
                534u -> Line("40", "Métro Montmorency / Chomedey", "#151f6d", "#ffffff", R.drawable.bus)
                15u -> Line("41", "Auteuil / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                536u -> Line("42", "Saint-François / Terminus Le Carrefour", "#151f6d", "#ffffff", R.drawable.bus)
                537u -> Line("43", "Auteuil / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                130u -> Line("45", "Auteuil / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
                539u -> Line("46", "Laval-Ouest / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
                132u -> Line("48", "Gare Vimont / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                541u -> Line("50", "Saint-Vincent-De-Paul / Terminus Le Carrefour", "#151f6d", "#ffffff", R.drawable.bus)
                134u -> Line("52", "Saint-François / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus)
                543u -> Line("55", "Laval-Ouest / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus)
                544u -> Line("56", "Métro Montmorency / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus)
                545u -> Line("58", "Saint-Vincent-De-Paul / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                138u -> Line("60", "Métro Cartier / Chomedey", "#151f6d", "#ffffff", R.drawable.bus)
                547u -> Line("61", "Fabreville / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
                548u -> Line("63", "Gare Sainte-Rose / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                549u -> Line("65", "Gare Sainte-Rose / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
                550u -> Line("66", "Terminus Le Carrefour / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus)
                143u -> Line("70", "Métro Cartier / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
                552u -> Line("713", "Sainte-Dorothée / Métro Côte-Vertu", "#151f6d", "#ffffff", R.drawable.bus)
                144u -> Line("73", "Fabreville / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                554u -> Line("730", "Gare Sainte-Dorothée / Montréal", "#151f6d", "#ffffff", R.drawable.bus)
                145u -> Line("74", "Saint-François / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                556u -> Line("744", "Métro Côte-Vertu / Gare Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus)
                557u -> Line("76", "Métro Montmorency / Gare Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus)
                558u -> Line("901", "Saint-François / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus)
                559u -> Line("902", "Terminus Le Carrefour / Métro Côte-Vertu", "#151f6d", "#ffffff", R.drawable.bus)
                560u -> Line("903", "Gare Sainte-Dorothée / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
                193u -> Line("925", "Saint-François / Métro Radisson", "#151f6d", "#ffffff", R.drawable.bus)
                562u -> Line("942", "Saint-François / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
                else -> Line("", "STL Unknown ($id)", "#151f6d", "#ffffff", R.drawable.bus)
            }
        }

        private fun getSTLevisLineById(id: UInt): Line {
            // TODO Find ids of all lines
            //   (Id of the line is on 9bits so higher
            //   than 512u means it's not known yet)
            return when (id) {
                513u -> Line("11", "", "#0091b3", "#ffffff", R.drawable.bus)
                514u -> Line("111", "", "#7e4082", "#ffffff", R.drawable.bus)
                515u -> Line("115", "", "#7e4082", "#ffffff", R.drawable.bus)
                516u -> Line("119", "", "#7e4082", "#ffffff", R.drawable.bus)
                517u -> Line("11A", "", "#0091b3", "#ffffff", R.drawable.bus)
                518u -> Line("125", "", "#7e4082", "#ffffff", R.drawable.bus)
                519u -> Line("126", "", "#7e4082", "#ffffff", R.drawable.bus)
                520u -> Line("127", "", "#7e4082", "#ffffff", R.drawable.bus)
                521u -> Line("129", "", "#7e4082", "#ffffff", R.drawable.bus)
                522u -> Line("13", "", "#4ea685", "#ffffff", R.drawable.bus)
                523u -> Line("131", "", "#7e4082", "#ffffff", R.drawable.bus)
                524u -> Line("135", "", "#7e4082", "#ffffff", R.drawable.bus)
                525u -> Line("136", "", "#7e4082", "#ffffff", R.drawable.bus)
                526u -> Line("137", "", "#7e4082", "#ffffff", R.drawable.bus)
                527u -> Line("139", "", "#7e4082", "#ffffff", R.drawable.bus)
                528u -> Line("15", "", "#0091b3", "#ffffff", R.drawable.bus)
                529u -> Line("155", "", "#7e4082", "#ffffff", R.drawable.bus)
                530u -> Line("156", "", "#7e4082", "#ffffff", R.drawable.bus)
                531u -> Line("158", "", "#7e4082", "#ffffff", R.drawable.bus)
                532u -> Line("22", "", "#0091b3", "#ffffff", R.drawable.bus)
                533u -> Line("221", "", "#7e4082", "#ffffff", R.drawable.bus)
                534u -> Line("222", "", "#7e4082", "#ffffff", R.drawable.bus)
                535u -> Line("225", "", "#7e4082", "#ffffff", R.drawable.bus)
                536u -> Line("23", "", "#0091b3", "#ffffff", R.drawable.bus)
                537u -> Line("231", "", "#7e4082", "#ffffff", R.drawable.bus)
                538u -> Line("232", "", "#7e4082", "#ffffff", R.drawable.bus)
                539u -> Line("235", "", "#7e4082", "#ffffff", R.drawable.bus)
                540u -> Line("24", "", "#4ea685", "#ffffff", R.drawable.bus)
                541u -> Line("241", "", "#7e4082", "#ffffff", R.drawable.bus)
                542u -> Line("242", "", "#7e4082", "#ffffff", R.drawable.bus)
                543u -> Line("245", "", "#7e4082", "#ffffff", R.drawable.bus)
                544u -> Line("246", "", "#7e4082", "#ffffff", R.drawable.bus)
                545u -> Line("31", "", "#0091b3", "#ffffff", R.drawable.bus)
                546u -> Line("311", "", "#7e4082", "#ffffff", R.drawable.bus)
                547u -> Line("325", "", "#7e4082", "#ffffff", R.drawable.bus)
                548u -> Line("34", "", "#0091b3", "#ffffff", R.drawable.bus)
                549u -> Line("345", "", "#7e4082", "#ffffff", R.drawable.bus)
                550u -> Line("34E", "", "#ffa400", "#ffffff", R.drawable.bus)
                551u -> Line("35", "", "#0091b3", "#ffffff", R.drawable.bus)
                552u -> Line("351", "", "#7e4082", "#ffffff", R.drawable.bus)
                553u -> Line("355", "", "#7e4082", "#ffffff", R.drawable.bus)
                554u -> Line("36", "", "#0091b3", "#ffffff", R.drawable.bus)
                555u -> Line("36E", "", "#ffa400", "#ffffff", R.drawable.bus)
                556u -> Line("37", "", "#0091b3", "#ffffff", R.drawable.bus)
                557u -> Line("375", "", "#7e4082", "#ffffff", R.drawable.bus)
                558u -> Line("37E", "", "#ffa400", "#ffffff", R.drawable.bus)
                559u -> Line("38", "", "#0091b3", "#ffffff", R.drawable.bus)
                560u -> Line("381", "", "#7e4082", "#ffffff", R.drawable.bus)
                561u -> Line("385", "", "#7e4082", "#ffffff", R.drawable.bus)
                562u -> Line("38E", "", "#ffa400", "#ffffff", R.drawable.bus)
                563u -> Line("39", "", "#4ea685", "#ffffff", R.drawable.bus)
                564u -> Line("42E", "", "#ffa400", "#ffffff", R.drawable.bus)
                565u -> Line("43E", "", "#ffa400", "#ffffff", R.drawable.bus)
                566u -> Line("65", "", "#4ea685", "#ffffff", R.drawable.bus)
                567u -> Line("ECQ", "", "#ffa400", "#ffffff", R.drawable.bus)
                568u -> Line("ELQ", "", "#ffa400", "#ffffff", R.drawable.bus)
                569u -> Line("EOQ", "", "#ffa400", "#ffffff", R.drawable.bus)
                570u -> Line("ESQ", "", "#ffa400", "#ffffff", R.drawable.bus)
                571u -> Line("L1", "Lévisien 1", "#1e4289", "#ffffff", R.drawable.bus)
                572u -> Line("L2", "Lévisien 2", "#1e4289", "#ffffff", R.drawable.bus)
                573u -> Line("L3", "Lévisien 3", "#1e4289", "#ffffff", R.drawable.bus)
                else -> Line("", "STLévis Unknown ($id)", "#0091b3", "#ffffff", R.drawable.bus)
            }
        }
    }
}