package com.transition.ora.registries

import com.transition.ora.types.Line
import com.transition.ora.R


object LineRegistry {
    private val lineMapForSTM: Map<UInt, (zone: String) -> Line> = mapOf(
        1u to { Line("1", "Ligne Verte", "#00a553", "#ffffff", R.drawable.metro) },
        2u to { Line("2", "Ligne Orange", "#f2832c", "#ffffff", R.drawable.metro) },
        224u to { Line("2", "Ligne Orange (zone B)", "#f2832c", "#ffffff", R.drawable.metro) },
        3u to { zone -> Line("4", if (zone == "B") "Ligne Jaune (zone B)" else "Ligne Jaune", "#ffd200", "#000000", R.drawable.metro) },
        4u to { Line("5", "Ligne Bleue", "#0078d0", "#ffffff", R.drawable.metro) },
        5u to { Line("10", "De Lorimier", "#009ee0", "#ffffff", R.drawable.bus) },
        6u to { Line("11", "Parc-du-Mont-Royal / Ridgewood", "#009ee0", "#ffffff", R.drawable.bus) },
        7u to { Line("12", "Île-des-Soeurs", "#009ee0", "#ffffff", R.drawable.bus) },
        8u to { Line("13", "Christophe-Colomb", "#009ee0", "#ffffff", R.drawable.bus) },
        9u to { Line("14", "Atateken", "#009ee0", "#ffffff", R.drawable.bus) },
        10u to { Line("15", "Sainte-Catherine", "#009ee0", "#ffffff", R.drawable.bus) },
        11u to { Line("16", "Graham", "#009ee0", "#ffffff", R.drawable.bus) },
        12u to { Line("17", "Décarie", "#009ee0", "#ffffff", R.drawable.bus) },
        13u to { Line("18", "Beaubien", "#781b7d", "#ffffff", R.drawable.bus) },
        220u to { Line("19", "Chabanel / Marché Central", "#009ee0", "#ffffff", R.drawable.bus) },
        213u to { Line("21", "Place du Commerce", "#009ee0", "#ffffff", R.drawable.bus) },
        14u to { Line("22", "Notre-Dame", "#009ee0", "#ffffff", R.drawable.bus) },
        15u to { Line("24", "Sherbrooke", "#781b7d", "#ffffff", R.drawable.bus) },
        16u to { Line("25", "Angus", "#009ee0", "#ffffff", R.drawable.bus) },
        231u to { Line("26", "Mercier-Est", "#009ee0", "#ffffff", R.drawable.bus) },
        17u to { Line("27", "Boulevard Saint-Joseph", "#009ee0", "#ffffff", R.drawable.bus) },
        18u to { Line("28", "Honoré-Beaugrand", "#009ee0", "#ffffff", R.drawable.bus) },
        19u to { Line("29", "Rachel", "#009ee0", "#ffffff", R.drawable.bus) },
        20u to { Line("30", "Saint-Denis / Saint-Hubert", "#009ee0", "#ffffff", R.drawable.bus) },
        21u to { Line("31", "Saint-Denis", "#009ee0", "#ffffff", R.drawable.bus) },
        22u to { Line("32", "Lacordaire", "#781b7d", "#ffffff", R.drawable.bus) },
        23u to { Line("33", "Langelier", "#781b7d", "#ffffff", R.drawable.bus) },
        24u to { Line("34", "Sainte-Catherine", "#009ee0", "#ffffff", R.drawable.bus) },
        279u to { Line("35", "Griffintown", "#009ee0", "#ffffff", R.drawable.bus) },
        25u to { Line("36", "Monk", "#009ee0", "#ffffff", R.drawable.bus) },
        26u to { Line("37", "Jolicoeur", "#009ee0", "#ffffff", R.drawable.bus) },
        338u to { Line("38", "De l'Église", "#009ee0", "#ffffff", R.drawable.bus) },
        27u to { Line("39", "Des Grandes-Prairies", "#009ee0", "#ffffff", R.drawable.bus) },
        28u to { Line("40", "Henri-Bourassa-Est", "#009ee0", "#ffffff", R.drawable.bus) },
        226u to { Line("41", "Quartier Saint-Michel / Ahuntsic", "#009ee0", "#ffffff", R.drawable.bus) },
        29u to { Line("43", "Monselet", "#009ee0", "#ffffff", R.drawable.bus) },
        30u to { Line("44", "Armand-Bombardier", "#781b7d", "#ffffff", R.drawable.bus) },
        31u to { Line("45", "Papineau", "#781b7d", "#ffffff", R.drawable.bus) },
        32u to { Line("46", "Casgrain", "#009ee0", "#ffffff", R.drawable.bus) },
        33u to { Line("47", "Masson", "#009ee0", "#ffffff", R.drawable.bus) },
        34u to { Line("48", "Perras", "#781b7d", "#ffffff", R.drawable.bus) },
        35u to { Line("49", "Maurice-Duplessis", "#781b7d", "#ffffff", R.drawable.bus) },
        339u to { Line("50", "Vieux-Montréal / Vieux-Port", "#009ee0", "#ffffff", R.drawable.bus) },
        36u to { Line("51", "Édouard-Montpetit", "#781b7d", "#ffffff", R.drawable.bus) },
        37u to { Line("52", "de Liège", "#009ee0", "#ffffff", R.drawable.bus) },
        38u to { Line("53", "Boulevard Saint-Laurent", "#009ee0", "#ffffff", R.drawable.bus) },
        39u to { Line("54", "Charland / Chabanel", "#009ee0", "#ffffff", R.drawable.bus) },
        40u to { Line("55", "Boulevard Saint-Laurent", "#781b7d", "#ffffff", R.drawable.bus) },
        41u to { Line("56", "Saint-Hubert", "#009ee0", "#ffffff", R.drawable.bus) },
        42u to { Line("57", "Pointe-Saint-Charles", "#009ee0", "#ffffff", R.drawable.bus) },
        43u to { Line("58", "Wellington", "#009ee0", "#ffffff", R.drawable.bus) },
        44u to { Line("61", "Wellington", "#009ee0", "#ffffff", R.drawable.bus) },
        45u to { Line("63", "Girouard", "#009ee0", "#ffffff", R.drawable.bus) },
        46u to { Line("64", "Grenet", "#781b7d", "#ffffff", R.drawable.bus) },
        47u to { Line("66", "The Boulevard", "#009ee0", "#ffffff", R.drawable.bus) },
        48u to { Line("67", "Saint-Michel", "#781b7d", "#ffffff", R.drawable.bus) },
        49u to { Line("68", "Pierrefonds", "#009ee0", "#ffffff", R.drawable.bus) },
        50u to { Line("69", "Gouin", "#781b7d", "#ffffff", R.drawable.bus) },
        51u to { Line("70", "Bois-Franc", "#009ee0", "#ffffff", R.drawable.bus) },
        232u to { Line("71", "Du Centre", "#009ee0", "#ffffff", R.drawable.bus) },
        52u to { Line("72", "Alfred-Nobel", "#009ee0", "#ffffff", R.drawable.bus) },
        53u to { Line("73", "Dalton", "#009ee0", "#ffffff", R.drawable.bus) },
        54u to { Line("74", "Bridge", "#009ee0", "#ffffff", R.drawable.bus) },
        55u to { Line("75", "De la Commune", "#009ee0", "#ffffff", R.drawable.bus) },
        56u to { Line("76", "McArthur", "#009ee0", "#ffffff", R.drawable.bus) },
        57u to { Line("77", "Cégep Marie-Victorin", "#009ee0", "#ffffff", R.drawable.bus) },
        58u to { Line("78", "Laurendeau", "#009ee0", "#ffffff", R.drawable.bus) },
        59u to { Line("80", "Avenue du Parc", "#781b7d", "#ffffff", R.drawable.bus) },
        280u to { Line("81", "Saint-Jean-Baptiste", "#009ee0", "#ffffff", R.drawable.bus) },
        60u to { Line("85", "Hochelaga", "#009ee0", "#ffffff", R.drawable.bus) },
        61u to { Line("86", "Pointe-aux-Trembles", "#009ee0", "#ffffff", R.drawable.bus) },
        62u to { Line("86", "Gouin / Perras", "#009ee0", "#ffffff", R.drawable.bus) },
        63u to { Line("90", "Saint-Jacques", "#781b7d", "#ffffff", R.drawable.bus) },
        64u to { Line("92", "Jean-Talon Ouest", "#009ee0", "#ffffff", R.drawable.bus) },
        65u to { Line("93", "Jean-Talon", "#009ee0", "#ffffff", R.drawable.bus) },
        66u to { Line("94", "D'Iberville", "#009ee0", "#ffffff", R.drawable.bus) },
        67u to { Line("95", "Bélanger", "#009ee0", "#ffffff", R.drawable.bus) },
        68u to { Line("97", "Avenue-du-Mont-Royal", "#781b7d", "#ffffff", R.drawable.bus) },
        69u to { Line("99", "Villeray", "#009ee0", "#ffffff", R.drawable.bus) },
        70u to { Line("100", "Crémazie", "#009ee0", "#ffffff", R.drawable.bus) },
        71u to { Line("101", "Saint-Patrick", "#009ee0", "#ffffff", R.drawable.bus) },
        72u to { Line("102", "Somerled", "#009ee0", "#ffffff", R.drawable.bus) },
        73u to { Line("103", "Monkland", "#781b7d", "#ffffff", R.drawable.bus) },
        74u to { Line("104", "Cavendish", "#009ee0", "#ffffff", R.drawable.bus) },
        75u to { Line("105", "Sherbrooke", "#781b7d", "#ffffff", R.drawable.bus) },
        76u to { Line("106", "Newman", "#781b7d", "#ffffff", R.drawable.bus) },
        77u to { Line("107", "Verdun", "#781b7d", "#ffffff", R.drawable.bus) },
        78u to { Line("108", "Bannantyne", "#009ee0", "#ffffff", R.drawable.bus) },
        79u to { Line("109", "Boulevard Shevchenko", "#009ee0", "#ffffff", R.drawable.bus) },
        80u to { Line("110", "Centrale", "#009ee0", "#ffffff", R.drawable.bus) },
        81u to { Line("112", "Airlie", "#781b7d", "#ffffff", R.drawable.bus) },
        82u to { Line("113", "Lapierre", "#009ee0", "#ffffff", R.drawable.bus) },
        333u to { Line("114", "Angrignon", "#009ee0", "#ffffff", R.drawable.bus) },
        83u to { Line("115", "Paré", "#009ee0", "#ffffff", R.drawable.bus) },
        84u to { Line("116", "Lafleur / Norman", "#009ee0", "#ffffff", R.drawable.bus) },
        85u to { Line("117", "O'Brien", "#009ee0", "#ffffff", R.drawable.bus) },
        86u to { Line("119", "Rockland", "#009ee0", "#ffffff", R.drawable.bus) },
        87u to { Line("121", "Sauvé / Côte-Vertu", "#781b7d", "#ffffff", R.drawable.bus) },
        88u to { Line("123", "Dollard", "#009ee0", "#ffffff", R.drawable.bus) },
        89u to { Line("124", "Victoria", "#009ee0", "#ffffff", R.drawable.bus) },
        90u to { Line("125", "Ontario", "#009ee0", "#ffffff", R.drawable.bus) },
        91u to { Line("126", "Thimens / Grenet", "#009ee0", "#ffffff", R.drawable.bus) },
        92u to { Line("128", "Saint-Laurent", "#009ee0", "#ffffff", R.drawable.bus) },
        93u to { Line("129", "Côte-Sainte-Catherine", "#009ee0", "#ffffff", R.drawable.bus) },
        94u to { Line("131", "De l'Assomption", "#009ee0", "#ffffff", R.drawable.bus) },
        95u to { Line("132", "Viau", "#009ee0", "#ffffff", R.drawable.bus) },
        234u to { Line("136", "Viau", "#781b7d", "#ffffff", R.drawable.bus) },
        96u to { Line("135", "De l'Esplanade", "#009ee0", "#ffffff", R.drawable.bus) },
        97u to { Line("138", "Notre-Dame-de-Grâce", "#009ee0", "#ffffff", R.drawable.bus) },
        98u to { Line("139", "Pie-IX", "#009ee0", "#ffffff", R.drawable.bus) },
        99u to { Line("140", "Fleury", "#009ee0", "#ffffff", R.drawable.bus) },
        100u to { Line("141", "Jean-Talon Est", "#781b7d", "#ffffff", R.drawable.bus) },
        101u to { Line("143", "Métrobus Charleroi", "#009ee0", "#ffffff", R.drawable.bus) },
        102u to { Line("144", "Avenue des Pins", "#009ee0", "#ffffff", R.drawable.bus) },
        103u to { Line("146", "Christophe-Colomb / Meilleur", "#009ee0", "#ffffff", R.drawable.bus) },
        104u to { Line("148", "Métrobus Maurice-Duplessis", "#009ee0", "#ffffff", R.drawable.bus) },
        105u to { Line("150", "René-Lévesque", "#009ee0", "#ffffff", R.drawable.bus) },
        106u to { Line("159", "Métrobus Henri-Bourassa", "#009ee0", "#ffffff", R.drawable.bus) },
        107u to { Line("160", "Barclay", "#009ee0", "#ffffff", R.drawable.bus) },
        108u to { Line("161", "Van Horne", "#781b7d", "#ffffff", R.drawable.bus) },
        109u to { Line("162", "Westminster", "#009ee0", "#ffffff", R.drawable.bus) },
        110u to { Line("164", "Dudemaine", "#009ee0", "#ffffff", R.drawable.bus) },
        111u to { Line("165", "Côte-des-Neiges", "#781b7d", "#ffffff", R.drawable.bus) },
        112u to { Line("166", "Queen-Mary", "#009ee0", "#ffffff", R.drawable.bus) },
        113u to { Line("167", "Les Îles", "#009ee0", "#ffffff", R.drawable.bus) },
        114u to { Line("168", "Cité-du-Havre", "#009ee0", "#ffffff", R.drawable.bus) },
        115u to { Line("170", "Keller", "#009ee0", "#ffffff", R.drawable.bus) },
        116u to { Line("171", "Henri-Bourassa", "#781b7d", "#ffffff", R.drawable.bus) },
        323u to { Line("172", "Du Golf", "#009ee0", "#ffffff", R.drawable.bus) },
        117u to { Line("174", "Côte-Vertu-Ouest", "#009ee0", "#ffffff", R.drawable.bus) },
        118u to { Line("175", "Griffith / Saint-François", "#009ee0", "#ffffff", R.drawable.bus) },
        119u to { Line("176", "Berlioz", "#009ee0", "#ffffff", R.drawable.bus) },
        120u to { Line("177", "Thimens", "#009ee0", "#ffffff", R.drawable.bus) },
        235u to { Line("178", "Pointe-Nord / Île-des-Soeurs", "#009ee0", "#ffffff", R.drawable.bus) },
        121u to { Line("179", "De l'Acadie", "#009ee0", "#ffffff", R.drawable.bus) },
        122u to { Line("180", "De Salaberry", "#009ee0", "#ffffff", R.drawable.bus) },
        123u to { Line("182", "Métrobus Sherbrooke", "#009ee0", "#ffffff", R.drawable.bus) },
        124u to { Line("183", "Gouin Est", "#009ee0", "#ffffff", R.drawable.bus) },
        125u to { Line("184", "Métrobus Bout-de-l’Île", "#009ee0", "#ffffff", R.drawable.bus) },
        126u to { Line("185", "Sherbrooke", "#009ee0", "#ffffff", R.drawable.bus) },
        127u to { Line("186", "Sherbrooke-Est", "#009ee0", "#ffffff", R.drawable.bus) },
        128u to { Line("187", "René-Lévesque", "#781b7d", "#ffffff", R.drawable.bus) },
        129u to { Line("188", "Couture", "#009ee0", "#ffffff", R.drawable.bus) },
        130u to { Line("189", "Notre-Dame", "#009ee0", "#ffffff", R.drawable.bus) },
        131u to { Line("190", "Métrobus Lachine", "#009ee0", "#ffffff", R.drawable.bus) },
        335u to { Line("190", "Norman", "#009ee0", "#ffffff", R.drawable.bus) },
        132u to { Line("191", "Broadway / Provost", "#009ee0", "#ffffff", R.drawable.bus) },
        133u to { Line("192", "Robert", "#009ee0", "#ffffff", R.drawable.bus) },
        134u to { Line("193", "Jarry", "#781b7d", "#ffffff", R.drawable.bus) },
        135u to { Line("194", "Métrobus Rivière-des-Prairies", "#009ee0", "#ffffff", R.drawable.bus) },
        136u to { Line("195", "Sherbrooke / Notre-Dame", "#009ee0", "#ffffff", R.drawable.bus) },
        137u to { Line("196", "Parc-Industriel-Lachine", "#781b7d", "#ffffff", R.drawable.bus) },
        138u to { Line("197", "Rosemont", "#781b7d", "#ffffff", R.drawable.bus) },
        334u to { Line("198", "Broadway", "#009ee0", "#ffffff", R.drawable.bus) },
        139u to { Line("199", "Métrobus Lacordaire", "#009ee0", "#ffffff", R.drawable.bus) },
        140u to { Line("200", "Sainte-Anne-de-Bellevue", "#009ee0", "#ffffff", R.drawable.bus) },
        141u to { Line("201", "Saint-Charles / Saint-Jean", "#009ee0", "#ffffff", R.drawable.bus) },
        142u to { Line("202", "Dawson", "#009ee0", "#ffffff", R.drawable.bus) },
        143u to { Line("203", "Carson", "#009ee0", "#ffffff", R.drawable.bus) },
        144u to { Line("204", "Cardinal", "#009ee0", "#ffffff", R.drawable.bus) },
        145u to { Line("205", "Gouin", "#009ee0", "#ffffff", R.drawable.bus) },
        146u to { Line("206", "Roger-Pilon", "#009ee0", "#ffffff", R.drawable.bus) },
        147u to { Line("207", "Jacques-Bizard", "#009ee0", "#ffffff", R.drawable.bus) },
        148u to { Line("208", "Brunswick", "#009ee0", "#ffffff", R.drawable.bus) },
        149u to { Line("209", "Des Sources", "#009ee0", "#ffffff", R.drawable.bus) },
        150u to { Line("210", "Jonh Abbott", "#009ee0", "#ffffff", R.drawable.bus) },
        151u to { Line("211", "Bord-du-Lac", "#009ee0", "#ffffff", R.drawable.bus) },
        236u to { Line("212", "Sainte-Anne", "#009ee0", "#ffffff", R.drawable.bus) },
        152u to { Line("213", "Parc-Industriel-Saint-Laurent", "#009ee0", "#ffffff", R.drawable.bus) },
        153u to { Line("214", "Des Sources", "#009ee0", "#ffffff", R.drawable.bus) },
        154u to { Line("215", "Henri-Bourassa", "#009ee0", "#ffffff", R.drawable.bus) },
        155u to { Line("216", "Transcanadienne", "#009ee0", "#ffffff", R.drawable.bus) },
        156u to { Line("217", "Anse-à-l'Orme", "#009ee0", "#ffffff", R.drawable.bus) },
        157u to { Line("218", "Antoine-Faucon", "#009ee0", "#ffffff", R.drawable.bus) },
        158u to { Line("219", "Chemin Sainte-Marie", "#009ee0", "#ffffff", R.drawable.bus) },
        159u to { Line("220", "Kieran", "#009ee0", "#ffffff", R.drawable.bus) },
        160u to { Line("221", "Métrobus Lionel-Groulx", "#009ee0", "#ffffff", R.drawable.bus) },
        161u to { Line("225", "Hymus", "#009ee0", "#ffffff", R.drawable.bus) },
        162u to { Line("261", "Trainbus Saint-Charles", "#009ee0", "#ffffff", R.drawable.bus) },
        163u to { Line("265", "Trainbus Île-Bizard", "#009ee0", "#ffffff", R.drawable.bus) },
        164u to { Line("268", "Trainbus Pierrefonds", "#009ee0", "#ffffff", R.drawable.bus) },
        174u to { Line("350", "Verdun / LaSalle", "#000000", "#ffffff", R.drawable.bus) },
        228u to { Line("353", "Lacordaire / Maurice-Duplessis", "#000000", "#ffffff", R.drawable.bus) },
        229u to { Line("354", "Sainte-Anne-de-Bellevue / Centre-ville", "#000000", "#ffffff", R.drawable.bus) },
        175u to { Line("355", "Pie-IX", "#000000", "#ffffff", R.drawable.bus) },
        176u to { Line("356", "Lachine / YUL Aéroport / Des Sources", "#000000", "#ffffff", R.drawable.bus) },
        177u to { Line("357", "Saint-Michel", "#000000", "#ffffff", R.drawable.bus) },
        178u to { Line("358", "René-Lévesque", "#000000", "#ffffff", R.drawable.bus) },
        179u to { Line("359", "Papineau", "#000000", "#ffffff", R.drawable.bus) },
        180u to { Line("360", "Avenue des Pins", "#000000", "#ffffff", R.drawable.bus) },
        181u to { Line("361", "Saint-Denis", "#000000", "#ffffff", R.drawable.bus) },
        182u to { Line("362", "Hochelaga / Notre-Dame", "#000000", "#ffffff", R.drawable.bus) },
        183u to { Line("363", "Boulevard Saint-Laurent", "#000000", "#ffffff", R.drawable.bus) },
        184u to { Line("364", "Sherbrooke / Joseph-Renaud", "#000000", "#ffffff", R.drawable.bus) },
        185u to { Line("365", "Avenue du Parc", "#000000", "#ffffff", R.drawable.bus) },
        186u to { Line("368", "Avenue-du-Mont-Royal", "#000000", "#ffffff", R.drawable.bus) },
        187u to { Line("369", "Côte-des-Neiges", "#000000", "#ffffff", R.drawable.bus) },
        188u to { Line("370", "Rosemont", "#000000", "#ffffff", R.drawable.bus) },
        189u to { Line("371", "Décarie", "#000000", "#ffffff", R.drawable.bus) },
        190u to { Line("372", "Jean-Talon", "#000000", "#ffffff", R.drawable.bus) },
        230u to { Line("376", "Pierrefonds / Centre-ville", "#000000", "#ffffff", R.drawable.bus) },
        191u to { Line("378", "Sauvé / YUL Aéroport", "#000000", "#ffffff", R.drawable.bus) },
        192u to { Line("380", "Henri-Bourassa", "#000000", "#ffffff", R.drawable.bus) },
        193u to { Line("382", "Pierrefonds / Saint-Charles", "#000000", "#ffffff", R.drawable.bus) },
        237u to { Line("401", "Express Saint-Charles", "#009ee0", "#ffffff", R.drawable.bus) },
        261u to { Line("405", "Express Bord-du-Lac", "#009ee0", "#ffffff", R.drawable.bus) },
        238u to { Line("406", "Express Newman", "#781b7d", "#ffffff", R.drawable.bus) },
        239u to { Line("407", "Express Île-Bizard", "#009ee0", "#ffffff", R.drawable.bus) },
        240u to { Line("409", "Express Des Sources", "#009ee0", "#ffffff", R.drawable.bus) },
        165u to { Line("410", "Express Notre-Dame", "#009ee0", "#ffffff", R.drawable.bus) },
        241u to { Line("411", "Express Lionel-Groulx", "#009ee0", "#ffffff", R.drawable.bus) },
        242u to { Line("419", "Express John Abbott", "#009ee0", "#ffffff", R.drawable.bus) },
        166u to { Line("420", "Express Notre-Dame-de-Grâce", "#009ee0", "#ffffff", R.drawable.bus) },
        262u to { Line("425", "Express Anse-à-l'Orme", "#009ee0", "#ffffff", R.drawable.bus) },
        218u to { Line("427", "Express Saint-Joseph", "#009ee0", "#ffffff", R.drawable.bus) },
        276u to { Line("428", "Express Parcs industriels de l'Est", "#009ee0", "#ffffff", R.drawable.bus) },
        167u to { Line("430", "Express Pointe-aux-Trembles", "#009ee0", "#ffffff", R.drawable.bus) },
        243u to { Line("432", "Express Lacordaire", "#009ee0", "#ffffff", R.drawable.bus) },
        244u to { Line("435", "Express Du Parc / Côte-des-Neiges", "#009ee0", "#ffffff", R.drawable.bus) },
        245u to { zone -> Line("439", if (zone == "B") "Express Pie-IX (zone B)" else "Express Pie-IX", "#781b7d", "#ffffff", R.drawable.bus) },
        246u to { Line("440", "Express Charleroi", "#009ee0", "#ffffff", R.drawable.bus) },
        247u to { Line("444", "Express Cégep Marie-Victorin", "#009ee0", "#ffffff", R.drawable.bus) },
        282u to { Line("445", "Express Papineau", "#009ee0", "#ffffff", R.drawable.bus) },
        248u to { Line("448", "Express Maurice-Duplessis", "#009ee0", "#ffffff", R.drawable.bus) },
        249u to { Line("449", "Express Rivière-des-Prairies", "#009ee0", "#ffffff", R.drawable.bus) },
        168u to { Line("460", "Express Métropolitaine", "#009ee0", "#ffffff", R.drawable.bus) },
        283u to { Line("465", "Express Côte-des-Neiges", "#009ee0", "#ffffff", R.drawable.bus) },
        211u to { Line("467", "Express Saint-Michel", "#009ee0", "#ffffff", R.drawable.bus) },
        250u to { Line("468", "Express Pierrefonds / Gouin", "#009ee0", "#ffffff", R.drawable.bus) },
        251u to { Line("469", "Express Henri-Bourassa", "#009ee0", "#ffffff", R.drawable.bus) },
        169u to { Line("470", "Express Pierrefonds", "#781b7d", "#ffffff", R.drawable.bus) },
        263u to { Line("475", "Express Dollard-des-Ormeaux", "#009ee0", "#ffffff", R.drawable.bus) },
        170u to { Line("480", "Pointe-Nord / Île-des-Soeurs", "#009ee0", "#ffffff", R.drawable.bus) },
        284u to { Line("480", "Express du Parc", "#009ee0", "#ffffff", R.drawable.bus) },
        264u to { Line("485", "Express Antoine-Faucon", "#009ee0", "#ffffff", R.drawable.bus) },
        252u to { Line("486", "Express Sherbrooke", "#009ee0", "#ffffff", R.drawable.bus) },
        253u to { Line("487", "Express Bout-de-l'Île", "#009ee0", "#ffffff", R.drawable.bus) },
        254u to { Line("491", "Express Lachine", "#009ee0", "#ffffff", R.drawable.bus) },
        255u to { Line("495", "Express Lachine / LaSalle", "#009ee0", "#ffffff", R.drawable.bus) },
        256u to { Line("496", "Express Victoria", "#781b7d", "#ffffff", R.drawable.bus) },
        171u to { Line("505", "Voie réservée Pie-IX", "#009ee0", "#ffffff", R.drawable.bus) },
        172u to { Line("506", "Voie réservée Newman", "#009ee0", "#ffffff", R.drawable.bus) },
        173u to { Line("535", "Voie réservée Du Parc / Côte-des-Neiges", "#009ee0", "#ffffff", R.drawable.bus) },
        340u to { Line("568", "Navette REM - Île-des-Soeurs / Gare Centrale", "#72a300", "#ffffff", R.drawable.bus) },
        277u to { Line("711", "Parc-du-Mont-Royal / Oratoire", "#009ee0", "#ffffff", R.drawable.bus) },
        257u to { Line("715", "Vieux-Montréal / Vieux-Port", "#009ee0", "#ffffff", R.drawable.bus) },
        219u to { Line("747", "YUL Aéroport / Centre-Ville", "#009ee0", "#ffffff", R.drawable.bus) },
        258u to { Line("767", "La Ronde / Station Jean-Drapeau", "#009ee0", "#ffffff", R.drawable.bus) },
        259u to { Line("769", "La Ronde / Station Papineau", "#009ee0", "#ffffff", R.drawable.bus) },
        260u to { Line("777", "Jean-Drapeau / Casino / Bonaventure", "#009ee0", "#ffffff", R.drawable.bus) },
        296u to { Line("806", "Navette", "#009ee0", "#ffffff", R.drawable.bus) },
        207u to { Line("811", "Navette Services santé", "#009ee0", "#ffffff", R.drawable.bus) },
        300u to { Line("822", "Navette Longue-Pointe", "#009ee0", "#ffffff", R.drawable.bus) },
        336u to { Line("872", "Île-des-Soeurs", "#009ee0", "#ffffff", R.drawable.bus) },
        281u to { Line("968", "Trainbus Roxboro / Côte-Vertu", "#009ee0", "#ffffff", R.drawable.bus) }
    )

    private val lineMapForRTL: Map<UInt, Line> = mapOf(
        2u to Line("1", "Desaulniers / Victoria / Windsor", "#ce0037", "#ffe9d1", R.drawable.bus),
        3u to Line("3", "Secteur Laflèche", "#ce0037", "#ffe9d1", R.drawable.bus),
        4u to Line("4", "Taschereau / Payer / DIX30", "#ce0037", "#ffe9d1", R.drawable.bus),
        5u to Line("5", "Auteuil / Mtée St-Hubert / Maisonneuve", "#ce0037", "#ffe9d1", R.drawable.bus),
        8u to Line("6", "Victoria", "#ce0037", "#ffe9d1", R.drawable.bus),
        9u to Line("8", "Ch. Chambly / Cousineau / Promenades St-Bruno", "#ce0037", "#ffe9d1", R.drawable.bus),
        10u to Line("9", "Secteurs L-M St-Hubert", "#ce0037", "#ffe9d1", R.drawable.bus),
        11u to Line("10", "Roland-Therrien / Belcourt", "#ce0037", "#ffe9d1", R.drawable.bus),
        12u to Line("13", "Riverside / Secteurs P-V Brossard", "#ce0037", "#ffe9d1", R.drawable.bus),
        13u to Line("14", "Rome / DIX30", "#ce0037", "#ffe9d1", R.drawable.bus),
        14u to Line("15", "Riverside / Alexandra / Churchill", "#ce0037", "#ffe9d1", R.drawable.bus),
        16u to Line("16", "Nobert / King-George / Adoncour", "#ce0037", "#ffe9d1", R.drawable.bus),
        17u to Line("17", "Roland-Therrien / Roberval", "#ce0037", "#ffe9d1", R.drawable.bus),
        18u to Line("19", "Davis", "#ce0037", "#ffe9d1", R.drawable.bus),
        19u to Line("20", "Jean-Paul-Vincent / Beauharnois", "#ce0037", "#ffe9d1", R.drawable.bus),
        20u to Line("21", "Grande-Allée / du Quartier", "#ce0037", "#ffe9d1", R.drawable.bus),
        21u to Line("23", "Ste-Hélène / Jacques-Cartier", "#ce0037", "#ffe9d1", R.drawable.bus),
        22u to Line("28", "Ch. Chambly / Savane / ENA", "#ce0037", "#ffe9d1", R.drawable.bus),
        23u to Line("29", "Collectivité Nouvelle", "#ce0037", "#ffe9d1", R.drawable.bus),
        24u to Line("30", "Secteurs P-V Brossard", "#ce0037", "#ffe9d1", R.drawable.bus),
        25u to Line("31", "Secteurs R-S-T Brossard / St-Laurent", "#ce0037", "#ffe9d1", R.drawable.bus),
        26u to Line("32", "Secteur B Brossard / Mountainview", "#ce0037", "#ffe9d1", R.drawable.bus),
        28u to Line("33", "Secteurs M-N-O Brossard", "#ce0037", "#ffe9d1", R.drawable.bus),
        29u to Line("34", "Secteur A Brossard / Bellevue", "#ce0037", "#ffe9d1", R.drawable.bus),
        32u to Line("37", "Simard / du Béarn", "#ce0037", "#ffe9d1", R.drawable.bus),
        33u to Line("38", "Chevrier / Secteur B Brossard", "#ce0037", "#ffe9d1", R.drawable.bus),
        34u to Line("41", "Rome / Milan", "#ce0037", "#ffe9d1", R.drawable.bus),
        35u to Line("42", "Gaétan-Boucher / Parc de la Cité", "#ce0037", "#ffe9d1", R.drawable.bus),
        36u to Line("43", "Milan / Rome", "#ce0037", "#ffe9d1", R.drawable.bus),
        37u to Line("44", "Secteurs M-N-O Brossard", "#ce0037", "#ffe9d1", R.drawable.bus),
        40u to Line("46", "Secteurs R-S-T Brossard", "#ce0037", "#ffe9d1", R.drawable.bus),
        41u to Line("47", "Secteurs R-S-T Brossard", "#ce0037", "#ffe9d1", R.drawable.bus),
        44u to Line("49", "Secteurs R-S Brossard", "#ce0037", "#ffe9d1", R.drawable.bus),
        45u to Line("50", "Bienville / Orchard / Prince-Charles", "#ce0037", "#ffe9d1", R.drawable.bus),
        47u to Line("54", "Tiffin / St-Georges / Taschereau", "#ce0037", "#ffe9d1", R.drawable.bus),
        48u to Line("55", "Victoria / Wellington", "#ce0037", "#ffe9d1", R.drawable.bus),
        49u to Line("59", "Montgomery / Gareau", "#ce0037", "#ffe9d1", R.drawable.bus),
        320u to Line("60", "Milan / Gaétan-Boucher / Promenades St-Bruno", "#ce0037", "#ffe9d1", R.drawable.bus),
        50u to Line("61", "Boucherville / Station Radisson", "#ce0037", "#ffe9d1", R.drawable.bus),
        52u to Line("71", "Curé-Poirier", "#ce0037", "#ffe9d1", R.drawable.bus),
        53u to Line("73", "Joliette / de Lyon", "#ce0037", "#ffe9d1", R.drawable.bus),
        54u to Line("74", "St-Laurent / Secteur Bellerive", "#ce0037", "#ffe9d1", R.drawable.bus),
        55u to Line("75", "Quinn / Brébeuf", "#ce0037", "#ffe9d1", R.drawable.bus),
        56u to Line("77", "Taschereau / Coteau-Rouge / Cégep É.-Montpetit", "#ce0037", "#ffe9d1", R.drawable.bus),
        57u to Line("80", "De Montarville / Carrefour de la Rive-Sud", "#ce0037", "#ffe9d1", R.drawable.bus),
        58u to Line("81", "du Fort-St-Louis / Marie-Victorin", "#ce0037", "#ffe9d1", R.drawable.bus),
        59u to Line("82", "Marie-Victorin / du Fort-St-Louis", "#ce0037", "#ffe9d1", R.drawable.bus),
        60u to Line("83", "De Montarville / Samuel-De Champlain", "#ce0037", "#ffe9d1", R.drawable.bus),
        61u to Line("84", "Samuel-De Champlain / De Montarville", "#ce0037", "#ffe9d1", R.drawable.bus),
        62u to Line("85", "Îles-Percées / de Mortagne / de Gascogne", "#ce0037", "#ffe9d1", R.drawable.bus),
        63u to Line("86", "Samuel-De Champlain / De Montarville / TCV", "#ce0037", "#ffe9d1", R.drawable.bus),
        64u to Line("87", "Marie-Victorin / du Fort St-Louis / TCV", "#ce0037", "#ffe9d1", R.drawable.bus),
        65u to Line("88", "Ch. Chambly / Mountainview", "#ce0037", "#ffe9d1", R.drawable.bus),
        147u to Line("99", "Promenades St-Bruno / Saint-Bruno-de-Montarville", "#ce0037", "#ffe9d1", R.drawable.bus),
        70u to Line("123", "Jacques-Cartier / Parcs industriels", "#ce0037", "#ffe9d1", R.drawable.bus),
        71u to Line("132", "DIX30 / Parc de la Cité / Mountainview", "#ce0037", "#ffe9d1", R.drawable.bus),
        270u to Line("160", "Milan / Gaétan-Boucher / Centre-ville St-Bruno", "#ce0037", "#ffe9d1", R.drawable.bus),
        340u to Line("417", "Express Roland-Therrien / Roberval", "#ce0037", "#ffe9d1", R.drawable.bus),
        263u to Line("720", "Navette REM - Interstation Rive-Sud", "#72a300", "#ffffff", R.drawable.bus)
    )

    private val lineMapForEXO: Map<UInt, (zone: String) -> Line> = mapOf(
        1u to { Line("6", "Deux-Montagnes", "#f79e91", "#ffffff", R.drawable.train) },
        2u to { zone -> Line("11", if (zone != "" || zone.startsWith("?")) "Vaudreuil-Hudson (zone $zone)" else "Vaudreuil-Hudson", "#f16179", "#000000", R.drawable.train) },
        3u to { zone -> Line("12", if (zone != "" || zone.startsWith("?")) "Saint-Jérôme (zone $zone)" else "Saint-Jérôme", "#fed16d", "#000000", R.drawable.train) },
        4u to { zone -> Line("13", if (zone != "" || zone.startsWith("?")) "Mont-Saint-Hilaire (zone $zone)" else "Mont-Saint-Hilaire", "#999ac6", "#000000", R.drawable.train) },
        5u to { zone -> Line("14", if (zone != "" || zone.startsWith("?")) "Candiac (zone $zone)" else "Candiac", "#5ab6b2", "#000000", R.drawable.train) },
        7u to { zone -> Line("15", if (zone != "" || zone.startsWith("?")) "Mascouche (zone $zone)" else "Mascouche", "#ca5898", "#000000", R.drawable.train) }
    )

    private val lineMapForRTC: Map<UInt, Line> = mapOf(
        1u to Line("1", "Station Belvédère - Gare fluviale / Cap-Blanc", "#013888", "#FFFFFF", R.drawable.bus),
        2u to Line("3", "Grand Théâtre - 41e Rue Est / Jean-Talon Ouest", "#013888", "#FFFFFF", R.drawable.bus),
        3u to Line("4", "Place Jacques-Cartier - Maizerets", "#013888", "#FFFFFF", R.drawable.bus),
        6u to Line("9", "Parcs Jean-Talon Nord et Duberger - Place Jacques-Cartier", "#013888", "#FFFFFF", R.drawable.bus),
        7u to Line("11", "Gare fluviale - Pointe-de-Sainte-Foy", "#013888", "#FFFFFF", R.drawable.bus),
        9u to Line("13", "Saint-Louis/Sainte-Foy Centre/du Versant-Nord - Du Versant-Nord/Sainte-Foy Centre/Saint-Louis", "#013888", "#FFFFFF", R.drawable.bus),
        11u to Line("16", "Sillery / U. Laval / Sainte-Foy Centre - U. Laval / Sillery / Sainte-Foy Centre", "#013888", "#FFFFFF", R.drawable.bus),
        12u to Line("18", "Gare du Palais - Université Laval", "#013888", "#FFFFFF", R.drawable.bus),
        316u to Line("19", "Grand Théâtre - Limoilou", "#013888", "#FFFFFF", R.drawable.bus),
        13u to Line("22", "Sainte-Foy Centre - Terminus Les Saules", "#013888", "#FFFFFF", R.drawable.bus),
        15u to Line("25", "Place D'Youville / Gare du Palais - Pointe-de-Sainte-Foy", "#013888", "#FFFFFF", R.drawable.bus),
        16u to Line("28", "Colline Parlementaire - 51e Rue Est", "#013888", "#FFFFFF", R.drawable.bus),
        17u to Line("29", "Parc Colbert Est - Place Jacques-Cartier", "#013888", "#FFFFFF", R.drawable.bus),
        18u to Line("31", "Terminus de la Faune - Lac-Saint-Charles", "#013888", "#FFFFFF", R.drawable.bus),
        19u to Line("32", "Terminus de la Faune - Lac Clément", "#013888", "#FFFFFF", R.drawable.bus),
        20u to Line("33", "Parc industriel Charlesbourg - Terminus de la Faune", "#013888", "#FFFFFF", R.drawable.bus),
        21u to Line("34", "Terminus de la Faune - Des Laurentides", "#013888", "#FFFFFF", R.drawable.bus),
        22u to Line("36", "Place Jacques-Cartier - Station des Roses", "#013888", "#FFFFFF", R.drawable.bus),
        25u to Line("39", "41e Rue Est - Terminus de la Faune", "#013888", "#FFFFFF", R.drawable.bus),
        321u to Line("51", "Parc O-Bus Sainte-Anne - Terminus Beauport", "#013888", "#FFFFFF", R.drawable.bus),
        27u to Line("52", "Maizerets - Terminus Charlesbourg", "#013888", "#FFFFFF", R.drawable.bus),
        28u to Line("53", "Courville - Terminus Beauport", "#013888", "#FFFFFF", R.drawable.bus),
        29u to Line("54", "Terminus Beauport / Vieux-Québec - Sainte-Thérèse-de-Lisieux", "#013888", "#FFFFFF", R.drawable.bus),
        30u to Line("55", "Terminus Beauport - Sainte-Thérèse-de-Lisieux", "#013888", "#FFFFFF", R.drawable.bus),
        31u to Line("57", "Sainte-Thérèse-de-Lisieux - Terminus Beauport", "#013888", "#FFFFFF", R.drawable.bus),
        32u to Line("58", "Terminus Beauport - Sainte-Thérèse-de-Lisieux", "#013888", "#FFFFFF", R.drawable.bus),
        33u to Line("59", "Terminus Charlesbourg - Terminus Chute-Montmorency", "#013888", "#FFFFFF", R.drawable.bus),
        171u to Line("61", "Maizerets - Lebourgneuf", "#013888", "#FFFFFF", R.drawable.bus),
        161u to Line("64", "Place Jacques-Cartier - Lebourgneuf", "#013888", "#FFFFFF", R.drawable.bus),
        162u to Line("65", "Place  J.-Cartier / colline Parlementaire - Lebourgneuf", "#013888", "#FFFFFF", R.drawable.bus),
        35u to Line("70", "Sainte-Foy Centre - Val-Bélair", "#013888", "#FFFFFF", R.drawable.bus),
        36u to Line("72", "Terminus Charlesbourg - Loretteville", "#013888", "#FFFFFF", R.drawable.bus),
        37u to Line("74", "Place Jacques-Cartier - Val-Bélair", "#013888", "#FFFFFF", R.drawable.bus),
        38u to Line("75", "Sainte-Foy Centre - Val-Bélair", "#013888", "#FFFFFF", R.drawable.bus),
        39u to Line("77", "Terminus Les Saules - Val-Bélair", "#013888", "#FFFFFF", R.drawable.bus),
        40u to Line("79", "Terminus Les Saules / Belvédère - Chauveau", "#013888", "#FFFFFF", R.drawable.bus),
        41u to Line("80", "Place Jacques-Cartier - Aéroport international Jean-Lesage", "#013888", "#FFFFFF", R.drawable.bus),
        42u to Line("81", "Terminus Les Saules - Terminus de la Faune", "#013888", "#FFFFFF", R.drawable.bus),
        43u to Line("82", "Place Jacques-Cartier - Lac-Saint-Charles", "#013888", "#FFFFFF", R.drawable.bus),
        44u to Line("84", "Place Jacques-Cartier - Val-Bélair", "#013888", "#FFFFFF", R.drawable.bus),
        45u to Line("85", "Place Jacques-Cartier - Lebourgneuf", "#013888", "#FFFFFF", R.drawable.bus),
        46u to Line("86", "Place J.-Cartier / colline Parlementaire - Terminus Les Saules", "#013888", "#FFFFFF", R.drawable.bus),
        47u to Line("88", "Sainte-Foy Centre - Terminus Les Saules", "#013888", "#FFFFFF", R.drawable.bus),
        48u to Line("92", "Cégep Garneau - Saint-Augustin", "#013888", "#FFFFFF", R.drawable.bus),
        49u to Line("93", "Sainte-Foy Centre/Univ.Laval/Cégep Garneau - Champigny", "#013888", "#FFFFFF", R.drawable.bus),
        53u to Line("133", "Vieux-Québec - Terminus de la Faune", "#013888", "#FFFFFF", R.drawable.bus),
        54u to Line("136", "Colline Parlementaire - Montagne-des-Roches", "#013888", "#FFFFFF", R.drawable.bus),
        55u to Line("185", "Station Belvédère / Sainte-Foy Centre - Neufchâtel", "#013888", "#FFFFFF", R.drawable.bus),
        56u to Line("214", "Gare du Palais - Cap-Rouge", "#E04503", "#000000", R.drawable.bus),
        57u to Line("215", "Gare du Palais - Cap-Rouge", "#E04503", "#000000", R.drawable.bus),
        58u to Line("230", "Colline Parlementaire - Terminus de la Faune", "#E04503", "#000000", R.drawable.bus),
        59u to Line("236", "Colline Parlementaire - Station des Roses", "#E04503", "#000000", R.drawable.bus),
        60u to Line("238", "Colline Parlementaire - Guillaume-Mathieu", "#E04503", "#000000", R.drawable.bus),
        61u to Line("239", "Colline Parlementaire - Terminus de la Faune", "#E04503", "#000000", R.drawable.bus),
        62u to Line("250", "Colline Parlementaire - Terminus Chute-Montmorency", "#E04503", "#000000", R.drawable.bus),
        63u to Line("251", "Colline Parlementaire - Parc-O-Bus Sainte-Anne", "#E04503", "#000000", R.drawable.bus),
        64u to Line("254", "Colline Parlementaire - Sainte-Thérèse-de-Lisieux", "#E04503", "#000000", R.drawable.bus),
        65u to Line("255", "Colline Parlementaire - Sainte-Thérèse-de-Lisieux", "#E04503", "#000000", R.drawable.bus),
        67u to Line("272", "Colline Parlementaire - Loretteville", "#E04503", "#000000", R.drawable.bus),
        168u to Line("289", "Colline Parlementaire - Saint-Émile", "#E04503", "#000000", R.drawable.bus),
        148u to Line("294", "Terminus Gare-du-Palais - Saint-Augustin", "#E04503", "#000000", R.drawable.bus),
        78u to Line("330", "Univ.Laval/Cégep Garneau - Terminus Charlesbourg", "#E04503", "#000000", R.drawable.bus),
        79u to Line("331", "Pointe-de-Sainte-Foy - Terminus de la Faune", "#E04503", "#000000", R.drawable.bus),
        80u to Line("332", "Saint-Rodrigue - Sainte-Foy Centre", "#E04503", "#000000", R.drawable.bus),
        81u to Line("336", "Univ.Laval/Cégep Garneau - Station des Roses", "#E04503", "#000000", R.drawable.bus),
        82u to Line("337", "Univ.Laval/Cégep Garneau - Terminus de la Faune", "#E04503", "#000000", R.drawable.bus),
        83u to Line("338", "Univ.Laval/Cégep Garneau - Montagne-des-Roches", "#E04503", "#000000", R.drawable.bus),
        84u to Line("350", "Univ.Laval/Cégep Garneau - Terminus Chute-Montmorency", "#E04503", "#000000", R.drawable.bus),
        90u to Line("382", "Univ.Laval/Cégep Garneau - Saint-Émile", "#E04503", "#000000", R.drawable.bus),
        91u to Line("384", "Univ.Laval/Cégep Garneau - Loretteville", "#E04503", "#000000", R.drawable.bus),
        94u to Line("391", "Pointe-de-Sainte-Foy - Terminus Les Saules", "#E04503", "#000000", R.drawable.bus),
        95u to Line("800", "Terminus Chute-Montmorency - Pointe-de-Sainte-Foy", "#97BF0D", "#000000", R.drawable.bus),
        96u to Line("801", "Terminus de la Faune - Pointe-de-Sainte-Foy", "#97BF0D", "#000000", R.drawable.bus),
        164u to Line("802", "Terminus Beauport - Station Belvédère", "#97BF0D", "#000000", R.drawable.bus),
        172u to Line("803", "Terminus Beauport - Terminus Les Saules", "#97BF0D", "#000000", R.drawable.bus),
        318u to Line("804", "Sainte-Foy Centre - Loretteville", "#97BF0D", "#000000", R.drawable.bus),
        317u to Line("807", "Place D'Youville - Pointe-de-Sainte-Foy", "#97BF0D", "#000000", R.drawable.bus),
        208u to Line("950", "Terminus Chute-Montmorency", "#1A171B", "#FFFFFF", R.drawable.bus)
    )

    private val lineMapForSTL: Map<UInt, Line> = mapOf(
        1u to Line("2", "Métro Henri-Bourassa / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus),
        2u to Line("12", "Pont-Viau / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        302u to Line("16", "Métro Montmorency / Laval-des-Rapides / Armand-Frappier", "#151f6d", "#ffffff", R.drawable.bus),
        3u to Line("17", "Auteuil / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        4u to Line("20", "Métro Cartier / Chomedey", "#151f6d", "#ffffff", R.drawable.bus),
        264u to Line("22", "Saint-François / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        5u to Line("24", "Métro Cartier / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        6u to Line("25", "Saint-François / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        7u to Line("26", "Métro Montmorency / Gare Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        8u to Line("27", "Gare Vimont / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        9u to Line("28", "Saint-Vincent-De-Paul / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        10u to Line("31", "Auteuil / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus),
        11u to Line("33", "Métro Montmorency / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        265u to Line("36", "Métro Montmorency / Chomedey", "#151f6d", "#ffffff", R.drawable.bus),
        12u to Line("37", "Sainte-Rose / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        13u to Line("39", "Auteuil / Terminus Le Carrefour", "#151f6d", "#ffffff", R.drawable.bus),
        14u to Line("40", "Métro Montmorency / Chomedey", "#151f6d", "#ffffff", R.drawable.bus),
        15u to Line("41", "Auteuil / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        16u to Line("42", "Saint-François / Terminus Le Carrefour", "#151f6d", "#ffffff", R.drawable.bus),
        129u to Line("43", "Auteuil / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        130u to Line("45", "Auteuil / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus),
        131u to Line("46", "Laval-Ouest / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus),
        132u to Line("48", "Gare Vimont / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        133u to Line("50", "Saint-Vincent-De-Paul / Terminus Le Carrefour", "#151f6d", "#ffffff", R.drawable.bus),
        134u to Line("52", "Saint-François / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus),
        135u to Line("55", "Laval-Ouest / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus),
        136u to Line("56", "Métro Montmorency / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        137u to Line("58", "Saint-Vincent-De-Paul / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        138u to Line("60", "Métro Cartier / Chomedey", "#151f6d", "#ffffff", R.drawable.bus),
        139u to Line("61", "Fabreville / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus),
        140u to Line("63", "Gare Sainte-Rose / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        141u to Line("65", "Gare Sainte-Rose / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus),
        142u to Line("66", "Terminus Le Carrefour / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        143u to Line("70", "Métro Cartier / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus),
        144u to Line("73", "Fabreville / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        145u to Line("74", "Saint-François / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        146u to Line("76", "Métro Montmorency / Gare Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        147u to Line("144", "Métro Côte-Vertu / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        148u to Line("151", "Sainte-Rose / Métro Côte-Vertu", "#151f6d", "#ffffff", R.drawable.bus),
        190u to Line("222", "Saint-Vincent-De-Paul / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        149u to Line("228", "Saint-Vincent-De-Paul / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        150u to Line("252", "Saint-François / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus),
        64u to Line("313", "Chomedey / Métro Côte-Vertu", "#151f6d", "#ffffff", R.drawable.bus),
        27u to Line("322", "Duvernay / Métro Henri-Bourassa", "#151f6d", "#ffffff", R.drawable.bus),
        151u to Line("402", "Sainte-Rose / Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        152u to Line("404", "Sainte-Dorothée / Gare Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        299u to Line("713", "Sainte-Dorothée / Métro Côte-Vertu", "#151f6d", "#ffffff", R.drawable.bus),
        290u to Line("730", "Gare Sainte-Dorothée / Montréal", "#151f6d", "#ffffff", R.drawable.bus),
        295u to Line("744", "Métro Côte-Vertu / Gare Sainte-Dorothée", "#151f6d", "#ffffff", R.drawable.bus),
        153u to Line("901", "Saint-François / Métro Cartier", "#151f6d", "#ffffff", R.drawable.bus),
        154u to Line("902", "Terminus Le Carrefour / Métro Côte-Vertu", "#151f6d", "#ffffff", R.drawable.bus),
        155u to Line("903", "Gare Sainte-Dorothée / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus),
        193u to Line("925", "Saint-François / Métro Radisson", "#151f6d", "#ffffff", R.drawable.bus),
        270u to Line("942", "Saint-François / Métro Montmorency", "#151f6d", "#ffffff", R.drawable.bus)
    )

    private val lineMapForEXOLaurentides: Map<UInt, Line> = mapOf(
        8u to Line("8", "Saint-Eustache - Laval (métro Montmorency)", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        9u to Line("9", "Saint-Jérôme / Laval", "#000000", "#ffffff", R.drawable.bus),
        11u to Line("11", "Laval / Rosemère / Sainte-Thérèse", "#000000", "#ffffff", R.drawable.bus),
        12u to Line("12", "Direction Bois-des-Filion", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        14u to Line("15", "Rosemère - Gare Rosemère", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        16u to Line("17", "Terrebonne - Gare Rosemère", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        19u to Line("20", "Terrebonne ouest - Gare Rosemère", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        21u to Line("22", "Bois-des-Filion - Sainte-Thérèse", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        22u to Line("23", "Sainte-Anne-des-Plaines - Sainte-Thérèse", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        23u to Line("24", "Sainte-Anne-des-Plaines - Laval (métro Cartier)", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        24u to Line("27", "Lorraine - Sainte-Thérèse", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        26u to Line("51", "Boisbriand Nord vers Boisbriand Sud", "#000000", "#ffffff", R.drawable.bus),
        27u to Line("52", "Boisbriand Sud vers Boisbriand Nord", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        28u to Line("60", "Sainte-Thérèse", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        29u to Line("61", "Sainte-Thérèse - secteur Bas Sainte-Thérèse", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        30u to Line("62", "Sainte-Thérèse - secteur des Mille-Îles", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        31u to Line("80", "Saint-Eustache - Pointe-Calumet", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        116u to Line("81", "Saint-Eustache - Pointe-Calumet", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        32u to Line("88", "Saint-Eustache / Sainte-Thérèse", "#000000", "#ffffff", R.drawable.bus),
        33u to Line("89", "Saint-Eustache - secteur Dubois", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        34u to Line("90", "Saint-Eustache - Arthur-Sauvé et Industriel", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        35u to Line("91", "Saint-Eustache - secteur est (Saint-Laurent)", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        36u to Line("92", "Saint-Eustache - secteur centre", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        37u to Line("93", "Saint-Eustache - Deux-Montagnes", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        125u to Line("100", "Saint-Jérôme - secteur Bellefeuille sud", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        126u to Line("101", "Saint-Jérôme - secteur Saint-Antoine", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        127u to Line("102", "Saint-Jérôme - secteur Lafontaine", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        128u to Line("103", "Saint-Jérôme - secteur Centre", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        129u to Line("105", "Saint-Jérôme - secteur Bellefeuille nord", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        130u to Line("107", "Saint-Jérôme - Bellefeuille sud (Lajeunesse)", "#1F1F1F", "#FFFFFF", R.drawable.bus)
    )

    private val lineMapForSTLevis: Map<UInt, Line> = mapOf(
        45u to Line("L2", "Lévisien 2", "#1E4289", "#FFFFFF", R.drawable.bus),
        89u to Line("L3,", "Lévisien 3", "#1E4289", "#FFFFFF", R.drawable.bus)
    )

    private val lineMapForEXOTerrebonneMascouche: Map<UInt, Line> = mapOf(
        1u to Line("1", "Terrebonne - Mascouche", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        2u to Line("2", "Terrebonne - Mascouche", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        3u to Line("3", "Terrebonne - Mascouche", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        4u to Line("5", "Terrebonne - Bois-des-Filion", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        6u to Line("8", "Terrebonne - secteur centre", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        7u to Line("9", "Terrebonne - secteur ouest", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        8u to Line("11", "Terrebonne - Lachenaie", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        9u to Line("14", "Terrebonne - La Plaine", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        12u to Line("17", "Terrebonne - La Plaine", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        13u to Line("18", "Terrebonne - Cité du sport - Cégep de Terrebonne", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        14u to Line("19", "Terrebonne / Terminus Montmorency", "#000000", "#ffffff", R.drawable.bus),
        15u to Line("20", "Terrebonne - Mascouche", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        16u to Line("21", "Terrebonne - Mascouche", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        17u to Line("23", "Terrebonne - Sainte-Thérèse (Cégep Lionel-Groulx)", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        19u to Line("25", "Terrebonne - Montréal", "#1F1F1F", "#FFFFFF", R.drawable.bus),
        21u to Line("40", "Lachenaie - Montréal - Terminus Radisson", "#1F1F1F", "#FFFFFF", R.drawable.bus)
    )

    private val lineMapForMRCJoliette: Map<UInt, Line> = mapOf(
        1u to Line("125", "Saint-Donat / Chertsey / Montréal", "#81a449", "#ffffff", R.drawable.bus)
    )

    private val lineMapForREM: Map<UInt, (zone: String) -> Line> = mapOf(
        2u to { zone -> Line("A", if (zone != "" && zone != "A") "Ligne A (zone $zone)" else "Ligne A", "#82bf00", "#000000", R.drawable.lightmetro) }
    )


    fun getLineForSTM(id: UInt, zone: String): Line? = lineMapForSTM[id]?.invoke(zone)
    fun getLineForRTL(id: UInt): Line? = lineMapForRTL[id]
    fun getLineForEXO(id: UInt, zone: String): Line? = lineMapForEXO[id]?.invoke(zone)
    fun getLineForRTC(id: UInt): Line? = lineMapForRTC[id]
    fun getLineForSTL(id: UInt): Line? = lineMapForSTL[id]
    fun getLineForExoChamblyRichelieuCarignan(id: UInt): Line? = null
    fun getLineForExoValleeRichelieu(id: UInt): Line? = null
    fun getLineForExoHautSaintLaurent(id: UInt): Line? = null
    fun getLineForExoSudOuest(id: UInt): Line? = null
    fun getLineForExoLeRichelain(id: UInt): Line? = null
    fun getLineForExoRoussillon(id: UInt): Line? = null
    fun getLineForExoSorelVarennes(id: UInt): Line? = null
    fun getLineForExoPresquIle(id: UInt): Line? = null
    fun getLineForEXOLaurentides(id: UInt): Line? = lineMapForEXOLaurentides[id]
    fun getLineForSTLevis(id: UInt): Line? = lineMapForSTLevis[id]
    fun getLineForExoSainteJulie(id: UInt): Line? = null
    fun getLineForEXOTerrebonneMascouche(id: UInt): Line? = lineMapForEXOTerrebonneMascouche[id]
    fun getLineForEXOLassomption(id: UInt): Line? = null
    fun getLineForMRCJoliette(id: UInt): Line? = lineMapForMRCJoliette[id]
    fun getLineForSTQ(id: UInt): Line? = null
    fun getLineForREM(id: UInt, zone: String): Line? = lineMapForREM[id]?.invoke(zone)
}